"""Add_dim_email_dim_feedback_and_fact_feedback

Revision ID: 0f8ebfb3c13e
Revises: f42c3dfe0b65
Create Date: 2025-05-14 04:22:34.466858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8ebfb3c13e'
down_revision: Union[str, None] = 'f42c3dfe0b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_email',
    sa.Column('email_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('email_id'),
    sa.UniqueConstraint('email_id'),
    schema='common_dim_schema'
    )
    op.create_table('dim_feedback',
    sa.Column('feedback_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('feedback_id'),
    sa.UniqueConstraint('feedback_id'),
    schema='game_xgame_drama_max_schema'
    )
    op.create_table('fact_feedback',
    sa.Column('fact_feedback_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('date_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('feedback_id', sa.Integer(), nullable=True),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['common_dim_schema.dim_email.email_id'], ),
    sa.ForeignKeyConstraint(['feedback_id'], ['game_xgame_drama_max_schema.dim_feedback.feedback_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_xgame_drama_max_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_xgame_drama_max_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('fact_feedback_id'),
    sa.UniqueConstraint('fact_feedback_id'),
    schema='game_xgame_drama_max_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_feedback', schema='game_xgame_drama_max_schema')
    op.drop_table('dim_feedback', schema='game_xgame_drama_max_schema')
    op.drop_table('dim_email', schema='common_dim_schema')
    # ### end Alembic commands ###
