"""edit fact_api_call

Revision ID: 198c8e4341cb
Revises: 9b301b4b3152
Create Date: 2025-03-25 04:33:25.927870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198c8e4341cb'
down_revision: Union[str, None] = '9b301b4b3152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dim_api_type', ['api_type_id'], schema='game_xgame_drama_max_schema')
    op.create_unique_constraint(None, 'fact_api_call', ['api_call_id'], schema='game_xgame_drama_max_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_api_call', schema='game_xgame_drama_max_schema', type_='unique')
    op.drop_constraint(None, 'dim_api_type', schema='game_xgame_drama_max_schema', type_='unique')
    # ### end Alembic commands ###
