"""add status and fact

Revision ID: 19b341ab987e
Revises: 53da164aef64
Create Date: 2025-04-21 03:28:46.464858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b341ab987e'
down_revision: Union[str, None] = '53da164aef64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_cancel_purchase_action',
    sa.Column('purchase_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('purchase_date_id', sa.Integer(), nullable=True),
    sa.Column('purchase_time_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('usd_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_position_id', sa.Integer(), nullable=True),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['common_dim_schema.dim_currency.currency_id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['game_xgame_drama_max_schema.dim_package.package_id'], ),
    sa.ForeignKeyConstraint(['purchase_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['purchase_position_id'], ['game_xgame_drama_max_schema.dim_game_position.game_position_id'], ),
    sa.ForeignKeyConstraint(['purchase_time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_xgame_drama_max_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_xgame_drama_max_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('purchase_id'),
    sa.UniqueConstraint('purchase_id'),
    schema='game_xgame_drama_max_schema'
    )
    op.add_column('fact_iap', sa.Column('status', sa.Boolean(), nullable=True), schema='game_xgame_drama_max_schema')
    op.create_unique_constraint(None, 'fact_movie_click', ['movie_click_id'], schema='game_xgame_drama_max_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_movie_click', schema='game_xgame_drama_max_schema', type_='unique')
    op.drop_column('fact_iap', 'status', schema='game_xgame_drama_max_schema')
    op.drop_table('fact_cancel_purchase_action', schema='game_xgame_drama_max_schema')
    # ### end Alembic commands ###
