"""add 100_250

Revision ID: 3e9baba5c17b
Revises: d9acdc7be769
Create Date: 2025-03-25 07:38:25.613914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9baba5c17b'
down_revision: Union[str, None] = 'd9acdc7be769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dim_movie_type', ['movie_type_id'], schema='game_xgame_drama_max_schema')
    op.alter_column('dim_package', 'package_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=True,
               schema='game_xgame_drama_max_schema')
    op.create_unique_constraint(None, 'fact_movie_info', ['movie_info_id'], schema='game_xgame_drama_max_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_movie_info', schema='game_xgame_drama_max_schema', type_='unique')
    op.alter_column('dim_package', 'package_name',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               schema='game_xgame_drama_max_schema')
    op.drop_constraint(None, 'dim_movie_type', schema='game_xgame_drama_max_schema', type_='unique')
    # ### end Alembic commands ###
