"""add language 

Revision ID: 3f31a8b3b20e
Revises: 19b341ab987e
Create Date: 2025-04-25 02:56:35.093877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f31a8b3b20e'
down_revision: Union[str, None] = '19b341ab987e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_language',
    sa.Column('language_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('language_code', sa.String(length=2), nullable=True),
    sa.Column('language_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('language_id'),
    sa.UniqueConstraint('language_id'),
    schema='common_dim_schema'
    )
    op.add_column('dim_user', sa.Column('language_id', sa.Integer(), nullable=True), schema='game_xgame_drama_max_schema')
    op.create_foreign_key(None, 'dim_user', 'dim_language', ['language_id'], ['language_id'], source_schema='game_xgame_drama_max_schema', referent_schema='common_dim_schema')
    op.create_unique_constraint(None, 'fact_cancel_purchase_action', ['purchase_id'], schema='game_xgame_drama_max_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_cancel_purchase_action', schema='game_xgame_drama_max_schema', type_='unique')
    op.drop_constraint(None, 'dim_user', schema='game_xgame_drama_max_schema', type_='foreignkey')
    op.drop_column('dim_user', 'language_id', schema='game_xgame_drama_max_schema')
    op.drop_table('dim_language', schema='common_dim_schema')
    # ### end Alembic commands ###
