"""edit column movie_place init_movie

Revision ID: 3fe3ba525bed
Revises: c5851adcb954
Create Date: 2025-03-26 02:13:35.657744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe3ba525bed'
down_revision: Union[str, None] = 'c5851adcb954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_movie_place', sa.Column('movie_place', sa.String(), nullable=True), schema='game_xgame_drama_max_schema')
    op.create_unique_constraint(None, 'dim_movie_place', ['movie_place_id'], schema='game_xgame_drama_max_schema')
    op.drop_column('dim_movie_place', 'movie_place_name', schema='game_xgame_drama_max_schema')
    op.create_unique_constraint(None, 'fact_init_movie', ['init_movie_id'], schema='game_xgame_drama_max_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_init_movie', schema='game_xgame_drama_max_schema', type_='unique')
    op.add_column('dim_movie_place', sa.Column('movie_place_name', sa.VARCHAR(), autoincrement=False, nullable=True), schema='game_xgame_drama_max_schema')
    op.drop_constraint(None, 'dim_movie_place', schema='game_xgame_drama_max_schema', type_='unique')
    op.drop_column('dim_movie_place', 'movie_place', schema='game_xgame_drama_max_schema')
    # ### end Alembic commands ###
