"""add movie info fact

Revision ID: 62c9d14bd514
Revises: 938a40802f27
Create Date: 2025-02-26 16:47:52.867703

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62c9d14bd514"
down_revision: Union[str, None] = "938a40802f27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS common_dim_schema"))
    op.execute(
        sa.text(
            "CREATE SCHEMA IF NOT EXISTS game_celebrity_check_challenge_prank_schema"
        )
    )
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS game_screw_puzzle_story_schema"))
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS game_supermarket_journey_schema"))
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS game_xgame_drama_max_schema"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dim_ad",
        sa.Column("ad_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ad_format", sa.String(length=100), nullable=True),
        sa.Column("ad_platform", sa.String(length=100), nullable=True),
        sa.Column("ad_network", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("ad_id"),
        sa.UniqueConstraint("ad_id"),
        schema="common_dim_schema",
    )
    op.create_table(
        "dim_currency",
        sa.Column("currency_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("currency_name", sa.String(length=100), nullable=False),
        sa.Column("currency_code", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("currency_id"),
        sa.UniqueConstraint("currency_code"),
        sa.UniqueConstraint("currency_id"),
        schema="common_dim_schema",
    )
    op.create_table(
        "dim_date",
        sa.Column("date_id", sa.Integer(), nullable=False),
        sa.Column("full_date", sa.Date(), nullable=True),
        sa.Column("day", sa.Integer(), nullable=True),
        sa.Column("month", sa.Integer(), nullable=True),
        sa.Column("quarter", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("weekday", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("date_id"),
        sa.UniqueConstraint("date_id"),
        schema="common_dim_schema",
    )
    op.create_table(
        "dim_device",
        sa.Column("device_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_info", sa.String(length=100), nullable=True),
        sa.Column("platform", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("device_id"),
        sa.UniqueConstraint("device_id"),
        schema="common_dim_schema",
    )
    op.create_table(
        "dim_event_type",
        sa.Column("event_type_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_name", sa.String(length=100), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("event_type_id"),
        sa.UniqueConstraint("event_type_id"),
        schema="common_dim_schema",
    )
    op.create_table(
        "dim_genre",
        sa.Column("genre_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("genre_name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("genre_id"),
        sa.UniqueConstraint("genre_id"),
        schema="common_dim_schema",
    )
    op.create_table(
        "dim_location",
        sa.Column("location_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("country_code", sa.String(length=50), nullable=True),
        sa.Column("city", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("location_id"),
        sa.UniqueConstraint("location_id"),
        schema="common_dim_schema",
    )
    op.create_table(
        "dim_platform",
        sa.Column("platform_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("platform_name", sa.String(length=100), nullable=True),
        sa.Column("platform_type", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("platform_id"),
        sa.UniqueConstraint("platform_id"),
        schema="common_dim_schema",
    )
    op.create_table(
        "dim_time",
        sa.Column("time_id", sa.Integer(), nullable=False),
        sa.Column("hour", sa.Integer(), nullable=True),
        sa.Column("minute", sa.Integer(), nullable=True),
        sa.Column("second", sa.Integer(), nullable=True),
        sa.Column("time_of_day", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("time_id"),
        sa.UniqueConstraint("time_id"),
        schema="common_dim_schema",
    )

    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS game_screw_puzzle_story_schema"))
    op.create_table(
        "dim_game_position",
        sa.Column("game_position_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("position", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("game_position_id"),
        sa.UniqueConstraint("game_position_id"),
        schema="game_celebrity_check_challenge_prank_schema",
    )
    op.create_table(
        "dim_item_type",
        sa.Column("item_type_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_type_name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("item_type_id"),
        sa.UniqueConstraint("item_type_id"),
        schema="game_celebrity_check_challenge_prank_schema",
    )
    op.create_table(
        "dim_level",
        sa.Column("level_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("level_number", sa.Integer(), nullable=True),
        sa.Column("mode", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("level_id"),
        sa.UniqueConstraint("level_id"),
        schema="game_celebrity_check_challenge_prank_schema",
    )
    op.create_table(
        "dim_movie_type",
        sa.Column("movie_type_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("movie_type_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("movie_type_id"),
        sa.UniqueConstraint("movie_type_id"),
        schema="game_celebrity_check_challenge_prank_schema",
    )
    op.create_table(
        "dim_package",
        sa.Column("package_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("package_name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("package_id"),
        sa.UniqueConstraint("package_id"),
        schema="game_celebrity_check_challenge_prank_schema",
    )
    op.create_table(
        "dim_show_type",
        sa.Column("show_type_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("show_type", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("show_type_id"),
        sa.UniqueConstraint("show_type_id"),
        schema="game_celebrity_check_challenge_prank_schema",
    )
    op.create_table(
        "dim_game_position",
        sa.Column("game_position_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("position", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("game_position_id"),
        sa.UniqueConstraint("game_position_id"),
        schema="game_screw_puzzle_story_schema",
    )
    op.create_table(
        "dim_item_type",
        sa.Column("item_type_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_type_name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("item_type_id"),
        sa.UniqueConstraint("item_type_id"),
        schema="game_screw_puzzle_story_schema",
    )
    op.create_table(
        "dim_level",
        sa.Column("level_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("level_number", sa.Integer(), nullable=True),
        sa.Column("mode", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("level_id"),
        sa.UniqueConstraint("level_id"),
        schema="game_screw_puzzle_story_schema",
    )
    op.create_table(
        "dim_package",
        sa.Column("package_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("package_name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("package_id"),
        sa.UniqueConstraint("package_id"),
        schema="game_screw_puzzle_story_schema",
    )
    op.create_table(
        "dim_show_type",
        sa.Column("show_type_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("show_type", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("show_type_id"),
        sa.UniqueConstraint("show_type_id"),
        schema="game_screw_puzzle_story_schema",
    )

    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS game_supermarket_journey_schema"))
    op.create_table(
        "dim_game_position",
        sa.Column("game_position_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("position", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("game_position_id"),
        sa.UniqueConstraint("game_position_id"),
        schema="game_supermarket_journey_schema",
    )
    op.create_table(
        "dim_item_type",
        sa.Column("item_type_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_type_name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("item_type_id"),
        sa.UniqueConstraint("item_type_id"),
        schema="game_supermarket_journey_schema",
    )
    op.create_table(
        "dim_level",
        sa.Column("level_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("level_number", sa.Integer(), nullable=True),
        sa.Column("mode", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("level_id"),
        sa.UniqueConstraint("level_id"),
        schema="game_supermarket_journey_schema",
    )
    op.create_table(
        "dim_package",
        sa.Column("package_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("package_name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("package_id"),
        sa.UniqueConstraint("package_id"),
        schema="game_supermarket_journey_schema",
    )
    op.create_table(
        "dim_show_type",
        sa.Column("show_type_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("show_type", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("show_type_id"),
        sa.UniqueConstraint("show_type_id"),
        schema="game_supermarket_journey_schema",
    )
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS game_xgame_drama_max_schema"))
    op.create_table(
        "dim_game_position",
        sa.Column("game_position_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("position", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("game_position_id"),
        sa.UniqueConstraint("game_position_id"),
        schema="game_xgame_drama_max_schema",
    )
    op.create_table(
        "dim_item_type",
        sa.Column("item_type_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_type_name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("item_type_id"),
        sa.UniqueConstraint("item_type_id"),
        schema="game_xgame_drama_max_schema",
    )
    op.create_table(
        "dim_level",
        sa.Column("level_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("level_number", sa.Integer(), nullable=True),
        sa.Column("mode", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("level_id"),
        sa.UniqueConstraint("level_id"),
        schema="game_xgame_drama_max_schema",
    )
    op.create_table(
        "dim_package",
        sa.Column("package_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("package_name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("package_id"),
        sa.UniqueConstraint("package_id"),
        schema="game_xgame_drama_max_schema",
    )
    op.create_table(
        "dim_show_type",
        sa.Column("show_type_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("show_type", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("show_type_id"),
        sa.UniqueConstraint("show_type_id"),
        schema="game_xgame_drama_max_schema",
    )
    op.create_table(
        "dim_game",
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=True),
        sa.Column("platform_id", sa.Integer(), nullable=False),
        sa.Column("package_name", sa.String(length=100), nullable=True),
        sa.Column("game_name", sa.String(length=100), nullable=True),
        sa.Column("start_date_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["common_dim_schema.dim_genre.genre_id"],
        ),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["common_dim_schema.dim_platform.platform_id"],
        ),
        sa.ForeignKeyConstraint(
            ["start_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.PrimaryKeyConstraint("game_id"),
        sa.UniqueConstraint("game_id"),
        schema="common_dim_schema",
    )
    op.create_table(
        "dim_item",
        sa.Column("item_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_name", sa.String(length=2500), nullable=True),
        sa.Column("item_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_type_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_item_type.item_type_id"],
        ),
        sa.PrimaryKeyConstraint("item_id"),
        sa.UniqueConstraint("item_id"),
        schema="game_celebrity_check_challenge_prank_schema",
    )
    op.create_table(
        "dim_user",
        sa.Column("user_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_uuid", sa.String(length=50), nullable=True),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.Column("registration_date_id", sa.Integer(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["common_dim_schema.dim_device.device_id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["common_dim_schema.dim_location.location_id"],
        ),
        sa.ForeignKeyConstraint(
            ["registration_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("user_id"),
        schema="game_celebrity_check_challenge_prank_schema",
    )
    op.create_table(
        "dim_item",
        sa.Column("item_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_name", sa.String(length=2500), nullable=True),
        sa.Column("item_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_type_id"],
            ["game_screw_puzzle_story_schema.dim_item_type.item_type_id"],
        ),
        sa.PrimaryKeyConstraint("item_id"),
        sa.UniqueConstraint("item_id"),
        schema="game_screw_puzzle_story_schema",
    )
    op.create_table(
        "dim_user",
        sa.Column("user_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_uuid", sa.String(length=50), nullable=True),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.Column("registration_date_id", sa.Integer(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["common_dim_schema.dim_device.device_id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["common_dim_schema.dim_location.location_id"],
        ),
        sa.ForeignKeyConstraint(
            ["registration_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("user_id"),
        schema="game_screw_puzzle_story_schema",
    )
    op.create_table(
        "dim_item",
        sa.Column("item_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_name", sa.String(length=2500), nullable=True),
        sa.Column("item_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_type_id"],
            ["game_supermarket_journey_schema.dim_item_type.item_type_id"],
        ),
        sa.PrimaryKeyConstraint("item_id"),
        sa.UniqueConstraint("item_id"),
        schema="game_supermarket_journey_schema",
    )
    op.create_table(
        "dim_user",
        sa.Column("user_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_uuid", sa.String(length=50), nullable=True),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.Column("registration_date_id", sa.Integer(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["common_dim_schema.dim_device.device_id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["common_dim_schema.dim_location.location_id"],
        ),
        sa.ForeignKeyConstraint(
            ["registration_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("user_id"),
        schema="game_supermarket_journey_schema",
    )
    op.create_table(
        "dim_item",
        sa.Column("item_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_name", sa.String(length=2500), nullable=True),
        sa.Column("item_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_type_id"],
            ["game_xgame_drama_max_schema.dim_item_type.item_type_id"],
        ),
        sa.PrimaryKeyConstraint("item_id"),
        sa.UniqueConstraint("item_id"),
        schema="game_xgame_drama_max_schema",
    )
    op.create_table(
        "dim_user",
        sa.Column("user_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_uuid", sa.String(length=50), nullable=True),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.Column("registration_date_id", sa.Integer(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["common_dim_schema.dim_device.device_id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["common_dim_schema.dim_location.location_id"],
        ),
        sa.ForeignKeyConstraint(
            ["registration_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("user_id"),
        schema="game_xgame_drama_max_schema",
    )
    op.execute(
        sa.text(
            "CREATE SCHEMA IF NOT EXISTS game_celebrity_check_challenge_prank_schema"
        )
    )
    op.create_table(
        "dim_game_version",
        sa.Column("version_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("version_number", sa.String(length=20), nullable=False),
        sa.Column("start_date_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["common_dim_schema.dim_game.game_id"],
        ),
        sa.ForeignKeyConstraint(
            ["start_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.PrimaryKeyConstraint("version_id"),
        sa.UniqueConstraint("version_id"),
        schema="game_celebrity_check_challenge_prank_schema",
    )
    op.create_table(
        "dim_game_version",
        sa.Column("version_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("version_number", sa.String(length=20), nullable=False),
        sa.Column("start_date_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["common_dim_schema.dim_game.game_id"],
        ),
        sa.ForeignKeyConstraint(
            ["start_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.PrimaryKeyConstraint("version_id"),
        sa.UniqueConstraint("version_id"),
        schema="game_screw_puzzle_story_schema",
    )
    op.create_table(
        "dim_game_version",
        sa.Column("version_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("version_number", sa.String(length=20), nullable=False),
        sa.Column("start_date_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["common_dim_schema.dim_game.game_id"],
        ),
        sa.ForeignKeyConstraint(
            ["start_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.PrimaryKeyConstraint("version_id"),
        sa.UniqueConstraint("version_id"),
        schema="game_supermarket_journey_schema",
    )
    op.create_table(
        "dim_game_version",
        sa.Column("version_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("version_number", sa.String(length=20), nullable=False),
        sa.Column("start_date_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["common_dim_schema.dim_game.game_id"],
        ),
        sa.ForeignKeyConstraint(
            ["start_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.PrimaryKeyConstraint("version_id"),
        sa.UniqueConstraint("version_id"),
        schema="game_xgame_drama_max_schema",
    )
    op.create_table(
        "fact_ad_view",
        sa.Column("ad_view_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("level_id", sa.Integer(), nullable=True),
        sa.Column("event_type_id", sa.Integer(), nullable=True),
        sa.Column("view_date_id", sa.Integer(), nullable=True),
        sa.Column("view_time_id", sa.Integer(), nullable=True),
        sa.Column("ad_position_id", sa.Integer(), nullable=True),
        sa.Column("ad_id", sa.Integer(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("load_time", sa.Integer(), nullable=True),
        sa.Column("rewarded", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ad_id"],
            ["common_dim_schema.dim_ad.ad_id"],
        ),
        sa.ForeignKeyConstraint(
            ["ad_position_id"],
            [
                "game_celebrity_check_challenge_prank_schema.dim_game_position.game_position_id"
            ],
        ),
        sa.ForeignKeyConstraint(
            ["event_type_id"],
            ["common_dim_schema.dim_event_type.event_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_level.level_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_game_version.version_id"],
        ),
        sa.ForeignKeyConstraint(
            ["view_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["view_time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.PrimaryKeyConstraint("ad_view_id"),
        sa.UniqueConstraint("ad_view_id"),
        schema="game_celebrity_check_challenge_prank_schema",
    )
    op.create_table(
        "fact_iap",
        sa.Column("iap_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("iap_date_id", sa.Integer(), nullable=True),
        sa.Column("iap_time_id", sa.Integer(), nullable=True),
        sa.Column("iap_position_id", sa.Integer(), nullable=True),
        sa.Column("show_type_id", sa.Integer(), nullable=True),
        sa.Column("package_id", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["iap_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["iap_position_id"],
            [
                "game_celebrity_check_challenge_prank_schema.dim_game_position.game_position_id"
            ],
        ),
        sa.ForeignKeyConstraint(
            ["iap_time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_package.package_id"],
        ),
        sa.ForeignKeyConstraint(
            ["show_type_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_show_type.show_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("iap_id"),
        sa.UniqueConstraint("iap_id"),
        schema="game_celebrity_check_challenge_prank_schema",
    )
    op.create_table(
        "fact_item_transaction",
        sa.Column("transaction_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("level_id", sa.Integer(), nullable=True),
        sa.Column("event_type_id", sa.Integer(), nullable=True),
        sa.Column("transaction_date_id", sa.Integer(), nullable=True),
        sa.Column("time_id", sa.Integer(), nullable=True),
        sa.Column("transaction_type", sa.String(length=20), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("game_position_id", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_type_id"],
            ["common_dim_schema.dim_event_type.event_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["game_position_id"],
            [
                "game_celebrity_check_challenge_prank_schema.dim_game_position.game_position_id"
            ],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_item.item_id"],
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_level.level_id"],
        ),
        sa.ForeignKeyConstraint(
            ["time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id"),
        sa.UniqueConstraint("transaction_id"),
        schema="game_celebrity_check_challenge_prank_schema",
    )
    op.create_table(
        "fact_movie_info",
        sa.Column("movie_info_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("movie_date_id", sa.Integer(), nullable=True),
        sa.Column("time_id", sa.Integer(), nullable=True),
        sa.Column("movie_id", sa.Integer(), nullable=True),
        sa.Column("movie_category", sa.Integer(), nullable=True),
        sa.Column("ep_id", sa.Integer(), nullable=True),
        sa.Column("time_watching", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["movie_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("movie_info_id"),
        sa.UniqueConstraint("movie_info_id"),
        schema="game_celebrity_check_challenge_prank_schema",
    )
    op.create_table(
        "fact_player_activity",
        sa.Column("activity_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("date_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Integer(), nullable=True),
        sa.Column("retention_day", sa.Integer(), nullable=True),
        sa.Column("active_day", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("activity_id"),
        sa.UniqueConstraint("activity_id"),
        schema="game_celebrity_check_challenge_prank_schema",
    )
    op.create_table(
        "fact_purchase_action",
        sa.Column("purchase_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("purchase_date_id", sa.Integer(), nullable=True),
        sa.Column("purchase_time_id", sa.Integer(), nullable=True),
        sa.Column("package_id", sa.Integer(), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("currency_id", sa.Integer(), nullable=True),
        sa.Column("usd_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("purchase_position_id", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["common_dim_schema.dim_currency.currency_id"],
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_package.package_id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_position_id"],
            [
                "game_celebrity_check_challenge_prank_schema.dim_game_position.game_position_id"
            ],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("purchase_id"),
        sa.UniqueConstraint("purchase_id"),
        schema="game_celebrity_check_challenge_prank_schema",
    )
    op.create_table(
        "fact_screen",
        sa.Column("screen_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("event_type_id", sa.Integer(), nullable=True),
        sa.Column("date_id", sa.Integer(), nullable=True),
        sa.Column("time_id", sa.Integer(), nullable=True),
        sa.Column("screen_name", sa.Integer(), nullable=True),
        sa.Column("id_item", sa.Integer(), nullable=True),
        sa.Column("total_duration", sa.Integer(), nullable=True),
        sa.Column("screen_session", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_type_id"],
            ["common_dim_schema.dim_event_type.event_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("screen_id"),
        sa.UniqueConstraint("screen_id"),
        schema="game_celebrity_check_challenge_prank_schema",
    )
    op.create_table(
        "fact_user_behavior",
        sa.Column("behavior_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("behavior_date_id", sa.Integer(), nullable=True),
        sa.Column("time_id", sa.Integer(), nullable=True),
        sa.Column("screen_name", sa.Integer(), nullable=True),
        sa.Column("id_item", sa.String(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["behavior_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_celebrity_check_challenge_prank_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("behavior_id"),
        sa.UniqueConstraint("behavior_id"),
        schema="game_celebrity_check_challenge_prank_schema",
    )
    op.create_table(
        "fact_ad_view",
        sa.Column("ad_view_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("level_id", sa.Integer(), nullable=True),
        sa.Column("event_type_id", sa.Integer(), nullable=True),
        sa.Column("view_date_id", sa.Integer(), nullable=True),
        sa.Column("view_time_id", sa.Integer(), nullable=True),
        sa.Column("ad_position_id", sa.Integer(), nullable=True),
        sa.Column("ad_id", sa.Integer(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("load_time", sa.Integer(), nullable=True),
        sa.Column("rewarded", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ad_id"],
            ["common_dim_schema.dim_ad.ad_id"],
        ),
        sa.ForeignKeyConstraint(
            ["ad_position_id"],
            ["game_screw_puzzle_story_schema.dim_game_position.game_position_id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_type_id"],
            ["common_dim_schema.dim_event_type.event_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["game_screw_puzzle_story_schema.dim_level.level_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_screw_puzzle_story_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_screw_puzzle_story_schema.dim_game_version.version_id"],
        ),
        sa.ForeignKeyConstraint(
            ["view_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["view_time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.PrimaryKeyConstraint("ad_view_id"),
        sa.UniqueConstraint("ad_view_id"),
        schema="game_screw_puzzle_story_schema",
    )
    op.create_table(
        "fact_iap",
        sa.Column("iap_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("iap_date_id", sa.Integer(), nullable=True),
        sa.Column("iap_time_id", sa.Integer(), nullable=True),
        sa.Column("iap_position_id", sa.Integer(), nullable=True),
        sa.Column("show_type_id", sa.Integer(), nullable=True),
        sa.Column("package_id", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["iap_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["iap_position_id"],
            ["game_screw_puzzle_story_schema.dim_game_position.game_position_id"],
        ),
        sa.ForeignKeyConstraint(
            ["iap_time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["game_screw_puzzle_story_schema.dim_package.package_id"],
        ),
        sa.ForeignKeyConstraint(
            ["show_type_id"],
            ["game_screw_puzzle_story_schema.dim_show_type.show_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_screw_puzzle_story_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_screw_puzzle_story_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("iap_id"),
        sa.UniqueConstraint("iap_id"),
        schema="game_screw_puzzle_story_schema",
    )
    op.create_table(
        "fact_item_transaction",
        sa.Column("transaction_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("level_id", sa.Integer(), nullable=True),
        sa.Column("event_type_id", sa.Integer(), nullable=True),
        sa.Column("transaction_date_id", sa.Integer(), nullable=True),
        sa.Column("time_id", sa.Integer(), nullable=True),
        sa.Column("transaction_type", sa.String(length=20), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("game_position_id", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_type_id"],
            ["common_dim_schema.dim_event_type.event_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["game_position_id"],
            ["game_screw_puzzle_story_schema.dim_game_position.game_position_id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["game_screw_puzzle_story_schema.dim_item.item_id"],
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["game_screw_puzzle_story_schema.dim_level.level_id"],
        ),
        sa.ForeignKeyConstraint(
            ["time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_screw_puzzle_story_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_screw_puzzle_story_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id"),
        sa.UniqueConstraint("transaction_id"),
        schema="game_screw_puzzle_story_schema",
    )
    op.create_table(
        "fact_level_event",
        sa.Column("level_event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("level_id", sa.Integer(), nullable=True),
        sa.Column("event_type_id", sa.Integer(), nullable=True),
        sa.Column("event_date_id", sa.Integer(), nullable=True),
        sa.Column("time_id", sa.Integer(), nullable=True),
        sa.Column("require_time", sa.Integer(), nullable=True),
        sa.Column("play_type", sa.String(), nullable=True),
        sa.Column("play_index", sa.Integer(), nullable=True),
        sa.Column("play_time", sa.Integer(), nullable=True),
        sa.Column("result", sa.String(), nullable=True),
        sa.Column("bonus_type", sa.String(), nullable=True),
        sa.Column("bonus_amount", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_type_id"],
            ["common_dim_schema.dim_event_type.event_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["game_screw_puzzle_story_schema.dim_level.level_id"],
        ),
        sa.ForeignKeyConstraint(
            ["time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_screw_puzzle_story_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_screw_puzzle_story_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("level_event_id"),
        sa.UniqueConstraint("level_event_id"),
        schema="game_screw_puzzle_story_schema",
    )
    op.create_table(
        "fact_player_action",
        sa.Column("action_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("level_id", sa.Integer(), nullable=True),
        sa.Column("action_date_id", sa.Integer(), nullable=True),
        sa.Column("time_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=25), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["action_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["game_screw_puzzle_story_schema.dim_level.level_id"],
        ),
        sa.ForeignKeyConstraint(
            ["time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_screw_puzzle_story_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_screw_puzzle_story_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("action_id"),
        sa.UniqueConstraint("action_id"),
        schema="game_screw_puzzle_story_schema",
    )
    op.create_table(
        "fact_player_activity",
        sa.Column("activity_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("date_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Integer(), nullable=True),
        sa.Column("retention_day", sa.Integer(), nullable=True),
        sa.Column("active_day", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_screw_puzzle_story_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_screw_puzzle_story_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("activity_id"),
        sa.UniqueConstraint("activity_id"),
        schema="game_screw_puzzle_story_schema",
    )
    op.create_table(
        "fact_purchase_action",
        sa.Column("purchase_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("purchase_date_id", sa.Integer(), nullable=True),
        sa.Column("purchase_time_id", sa.Integer(), nullable=True),
        sa.Column("package_id", sa.Integer(), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("currency_id", sa.Integer(), nullable=True),
        sa.Column("usd_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("purchase_position_id", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["common_dim_schema.dim_currency.currency_id"],
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["game_screw_puzzle_story_schema.dim_package.package_id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_position_id"],
            ["game_screw_puzzle_story_schema.dim_game_position.game_position_id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_screw_puzzle_story_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_screw_puzzle_story_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("purchase_id"),
        sa.UniqueConstraint("purchase_id"),
        schema="game_screw_puzzle_story_schema",
    )
    op.create_table(
        "fact_ad_view",
        sa.Column("ad_view_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("level_id", sa.Integer(), nullable=True),
        sa.Column("event_type_id", sa.Integer(), nullable=True),
        sa.Column("view_date_id", sa.Integer(), nullable=True),
        sa.Column("view_time_id", sa.Integer(), nullable=True),
        sa.Column("ad_position_id", sa.Integer(), nullable=True),
        sa.Column("ad_id", sa.Integer(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("load_time", sa.Integer(), nullable=True),
        sa.Column("rewarded", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ad_id"],
            ["common_dim_schema.dim_ad.ad_id"],
        ),
        sa.ForeignKeyConstraint(
            ["ad_position_id"],
            ["game_supermarket_journey_schema.dim_game_position.game_position_id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_type_id"],
            ["common_dim_schema.dim_event_type.event_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["game_supermarket_journey_schema.dim_level.level_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_supermarket_journey_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_supermarket_journey_schema.dim_game_version.version_id"],
        ),
        sa.ForeignKeyConstraint(
            ["view_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["view_time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.PrimaryKeyConstraint("ad_view_id"),
        sa.UniqueConstraint("ad_view_id"),
        schema="game_supermarket_journey_schema",
    )
    op.create_table(
        "fact_iap",
        sa.Column("iap_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("iap_date_id", sa.Integer(), nullable=True),
        sa.Column("iap_time_id", sa.Integer(), nullable=True),
        sa.Column("iap_position_id", sa.Integer(), nullable=True),
        sa.Column("show_type_id", sa.Integer(), nullable=True),
        sa.Column("package_id", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["iap_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["iap_position_id"],
            ["game_supermarket_journey_schema.dim_game_position.game_position_id"],
        ),
        sa.ForeignKeyConstraint(
            ["iap_time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["game_supermarket_journey_schema.dim_package.package_id"],
        ),
        sa.ForeignKeyConstraint(
            ["show_type_id"],
            ["game_supermarket_journey_schema.dim_show_type.show_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_supermarket_journey_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_supermarket_journey_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("iap_id"),
        sa.UniqueConstraint("iap_id"),
        schema="game_supermarket_journey_schema",
    )
    op.create_table(
        "fact_item_transaction",
        sa.Column("transaction_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("level_id", sa.Integer(), nullable=True),
        sa.Column("event_type_id", sa.Integer(), nullable=True),
        sa.Column("transaction_date_id", sa.Integer(), nullable=True),
        sa.Column("time_id", sa.Integer(), nullable=True),
        sa.Column("transaction_type", sa.String(length=20), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("game_position_id", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_type_id"],
            ["common_dim_schema.dim_event_type.event_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["game_position_id"],
            ["game_supermarket_journey_schema.dim_game_position.game_position_id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["game_supermarket_journey_schema.dim_item.item_id"],
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["game_supermarket_journey_schema.dim_level.level_id"],
        ),
        sa.ForeignKeyConstraint(
            ["time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_supermarket_journey_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_supermarket_journey_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id"),
        sa.UniqueConstraint("transaction_id"),
        schema="game_supermarket_journey_schema",
    )
    op.create_table(
        "fact_level_event",
        sa.Column("level_event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("level_id", sa.Integer(), nullable=True),
        sa.Column("event_type_id", sa.Integer(), nullable=True),
        sa.Column("event_date_id", sa.Integer(), nullable=True),
        sa.Column("time_id", sa.Integer(), nullable=True),
        sa.Column("require_time", sa.Integer(), nullable=True),
        sa.Column("play_type", sa.String(), nullable=True),
        sa.Column("play_index", sa.Integer(), nullable=True),
        sa.Column("play_time", sa.Integer(), nullable=True),
        sa.Column("result", sa.String(), nullable=True),
        sa.Column("bonus_type", sa.String(), nullable=True),
        sa.Column("bonus_amount", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_type_id"],
            ["common_dim_schema.dim_event_type.event_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["game_supermarket_journey_schema.dim_level.level_id"],
        ),
        sa.ForeignKeyConstraint(
            ["time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_supermarket_journey_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_supermarket_journey_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("level_event_id"),
        sa.UniqueConstraint("level_event_id"),
        schema="game_supermarket_journey_schema",
    )
    op.create_table(
        "fact_player_action",
        sa.Column("action_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("level_id", sa.Integer(), nullable=True),
        sa.Column("action_date_id", sa.Integer(), nullable=True),
        sa.Column("time_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=25), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["action_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["game_supermarket_journey_schema.dim_level.level_id"],
        ),
        sa.ForeignKeyConstraint(
            ["time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_supermarket_journey_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_supermarket_journey_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("action_id"),
        sa.UniqueConstraint("action_id"),
        schema="game_supermarket_journey_schema",
    )
    op.create_table(
        "fact_player_activity",
        sa.Column("activity_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("date_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Integer(), nullable=True),
        sa.Column("retention_day", sa.Integer(), nullable=True),
        sa.Column("active_day", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_supermarket_journey_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_supermarket_journey_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("activity_id"),
        sa.UniqueConstraint("activity_id"),
        schema="game_supermarket_journey_schema",
    )
    op.create_table(
        "fact_purchase_action",
        sa.Column("purchase_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("purchase_date_id", sa.Integer(), nullable=True),
        sa.Column("purchase_time_id", sa.Integer(), nullable=True),
        sa.Column("package_id", sa.Integer(), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("currency_id", sa.Integer(), nullable=True),
        sa.Column("usd_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("purchase_position_id", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["common_dim_schema.dim_currency.currency_id"],
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["game_supermarket_journey_schema.dim_package.package_id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_position_id"],
            ["game_supermarket_journey_schema.dim_game_position.game_position_id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_supermarket_journey_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_supermarket_journey_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("purchase_id"),
        sa.UniqueConstraint("purchase_id"),
        schema="game_supermarket_journey_schema",
    )
    op.create_table(
        "fact_ad_view",
        sa.Column("ad_view_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("level_id", sa.Integer(), nullable=True),
        sa.Column("event_type_id", sa.Integer(), nullable=True),
        sa.Column("view_date_id", sa.Integer(), nullable=True),
        sa.Column("view_time_id", sa.Integer(), nullable=True),
        sa.Column("ad_position_id", sa.Integer(), nullable=True),
        sa.Column("ad_id", sa.Integer(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("load_time", sa.Integer(), nullable=True),
        sa.Column("rewarded", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ad_id"],
            ["common_dim_schema.dim_ad.ad_id"],
        ),
        sa.ForeignKeyConstraint(
            ["ad_position_id"],
            ["game_xgame_drama_max_schema.dim_game_position.game_position_id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_type_id"],
            ["common_dim_schema.dim_event_type.event_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["game_xgame_drama_max_schema.dim_level.level_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_xgame_drama_max_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_xgame_drama_max_schema.dim_game_version.version_id"],
        ),
        sa.ForeignKeyConstraint(
            ["view_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["view_time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.PrimaryKeyConstraint("ad_view_id"),
        sa.UniqueConstraint("ad_view_id"),
        schema="game_xgame_drama_max_schema",
    )
    op.create_table(
        "fact_iap",
        sa.Column("iap_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("iap_date_id", sa.Integer(), nullable=True),
        sa.Column("iap_time_id", sa.Integer(), nullable=True),
        sa.Column("iap_position_id", sa.Integer(), nullable=True),
        sa.Column("show_type_id", sa.Integer(), nullable=True),
        sa.Column("package_id", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["iap_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["iap_position_id"],
            ["game_xgame_drama_max_schema.dim_game_position.game_position_id"],
        ),
        sa.ForeignKeyConstraint(
            ["iap_time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["game_xgame_drama_max_schema.dim_package.package_id"],
        ),
        sa.ForeignKeyConstraint(
            ["show_type_id"],
            ["game_xgame_drama_max_schema.dim_show_type.show_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_xgame_drama_max_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_xgame_drama_max_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("iap_id"),
        sa.UniqueConstraint("iap_id"),
        schema="game_xgame_drama_max_schema",
    )
    op.create_table(
        "fact_item_transaction",
        sa.Column("transaction_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("level_id", sa.Integer(), nullable=True),
        sa.Column("event_type_id", sa.Integer(), nullable=True),
        sa.Column("transaction_date_id", sa.Integer(), nullable=True),
        sa.Column("time_id", sa.Integer(), nullable=True),
        sa.Column("transaction_type", sa.String(length=20), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("game_position_id", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_type_id"],
            ["common_dim_schema.dim_event_type.event_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["game_position_id"],
            ["game_xgame_drama_max_schema.dim_game_position.game_position_id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["game_xgame_drama_max_schema.dim_item.item_id"],
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["game_xgame_drama_max_schema.dim_level.level_id"],
        ),
        sa.ForeignKeyConstraint(
            ["time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_xgame_drama_max_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_xgame_drama_max_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id"),
        sa.UniqueConstraint("transaction_id"),
        schema="game_xgame_drama_max_schema",
    )
    op.create_table(
        "fact_player_activity",
        sa.Column("activity_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("date_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Integer(), nullable=True),
        sa.Column("retention_day", sa.Integer(), nullable=True),
        sa.Column("active_day", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_xgame_drama_max_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_xgame_drama_max_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("activity_id"),
        sa.UniqueConstraint("activity_id"),
        schema="game_xgame_drama_max_schema",
    )
    op.create_table(
        "fact_purchase_action",
        sa.Column("purchase_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("purchase_date_id", sa.Integer(), nullable=True),
        sa.Column("purchase_time_id", sa.Integer(), nullable=True),
        sa.Column("package_id", sa.Integer(), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("currency_id", sa.Integer(), nullable=True),
        sa.Column("usd_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("purchase_position_id", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["common_dim_schema.dim_currency.currency_id"],
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["game_xgame_drama_max_schema.dim_package.package_id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_position_id"],
            ["game_xgame_drama_max_schema.dim_game_position.game_position_id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_xgame_drama_max_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_xgame_drama_max_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("purchase_id"),
        sa.UniqueConstraint("purchase_id"),
        schema="game_xgame_drama_max_schema",
    )
    op.create_table(
        "fact_screen",
        sa.Column("screen_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("event_type_id", sa.Integer(), nullable=True),
        sa.Column("date_id", sa.Integer(), nullable=True),
        sa.Column("time_id", sa.Integer(), nullable=True),
        sa.Column("screen_name", sa.Integer(), nullable=True),
        sa.Column("id_item", sa.Integer(), nullable=True),
        sa.Column("total_duration", sa.Integer(), nullable=True),
        sa.Column("screen_session", sa.Integer(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_type_id"],
            ["common_dim_schema.dim_event_type.event_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_xgame_drama_max_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_xgame_drama_max_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("screen_id"),
        sa.UniqueConstraint("screen_id"),
        schema="game_xgame_drama_max_schema",
    )
    op.create_table(
        "fact_user_behavior",
        sa.Column("behavior_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=True),
        sa.Column("behavior_date_id", sa.Integer(), nullable=True),
        sa.Column("time_id", sa.Integer(), nullable=True),
        sa.Column("screen_name", sa.Integer(), nullable=True),
        sa.Column("id_item", sa.String(), nullable=True),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["behavior_date_id"],
            ["common_dim_schema.dim_date.date_id"],
        ),
        sa.ForeignKeyConstraint(
            ["time_id"],
            ["common_dim_schema.dim_time.time_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game_xgame_drama_max_schema.dim_user.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["game_xgame_drama_max_schema.dim_game_version.version_id"],
        ),
        sa.PrimaryKeyConstraint("behavior_id"),
        sa.UniqueConstraint("behavior_id"),
        schema="game_xgame_drama_max_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fact_user_behavior", schema="game_xgame_drama_max_schema")
    op.drop_table("fact_screen", schema="game_xgame_drama_max_schema")
    op.drop_table("fact_purchase_action", schema="game_xgame_drama_max_schema")
    op.drop_table("fact_player_activity", schema="game_xgame_drama_max_schema")
    op.drop_table("fact_item_transaction", schema="game_xgame_drama_max_schema")
    op.drop_table("fact_iap", schema="game_xgame_drama_max_schema")
    op.drop_table("fact_ad_view", schema="game_xgame_drama_max_schema")
    op.drop_table("fact_purchase_action", schema="game_supermarket_journey_schema")
    op.drop_table("fact_player_activity", schema="game_supermarket_journey_schema")
    op.drop_table("fact_player_action", schema="game_supermarket_journey_schema")
    op.drop_table("fact_level_event", schema="game_supermarket_journey_schema")
    op.drop_table("fact_item_transaction", schema="game_supermarket_journey_schema")
    op.drop_table("fact_iap", schema="game_supermarket_journey_schema")
    op.drop_table("fact_ad_view", schema="game_supermarket_journey_schema")
    op.drop_table("fact_purchase_action", schema="game_screw_puzzle_story_schema")
    op.drop_table("fact_player_activity", schema="game_screw_puzzle_story_schema")
    op.drop_table("fact_player_action", schema="game_screw_puzzle_story_schema")
    op.drop_table("fact_level_event", schema="game_screw_puzzle_story_schema")
    op.drop_table("fact_item_transaction", schema="game_screw_puzzle_story_schema")
    op.drop_table("fact_iap", schema="game_screw_puzzle_story_schema")
    op.drop_table("fact_ad_view", schema="game_screw_puzzle_story_schema")
    op.drop_table(
        "fact_user_behavior", schema="game_celebrity_check_challenge_prank_schema"
    )
    op.drop_table("fact_screen", schema="game_celebrity_check_challenge_prank_schema")
    op.drop_table(
        "fact_purchase_action", schema="game_celebrity_check_challenge_prank_schema"
    )
    op.drop_table(
        "fact_player_activity", schema="game_celebrity_check_challenge_prank_schema"
    )
    op.drop_table(
        "fact_movie_info", schema="game_celebrity_check_challenge_prank_schema"
    )
    op.drop_table(
        "fact_item_transaction", schema="game_celebrity_check_challenge_prank_schema"
    )
    op.drop_table("fact_iap", schema="game_celebrity_check_challenge_prank_schema")
    op.drop_table("fact_ad_view", schema="game_celebrity_check_challenge_prank_schema")
    op.drop_table("dim_game_version", schema="game_xgame_drama_max_schema")
    op.drop_table("dim_game_version", schema="game_supermarket_journey_schema")
    op.drop_table("dim_game_version", schema="game_screw_puzzle_story_schema")
    op.drop_table(
        "dim_game_version", schema="game_celebrity_check_challenge_prank_schema"
    )
    op.drop_table("dim_user", schema="game_xgame_drama_max_schema")
    op.drop_table("dim_item", schema="game_xgame_drama_max_schema")
    op.drop_table("dim_user", schema="game_supermarket_journey_schema")
    op.drop_table("dim_item", schema="game_supermarket_journey_schema")
    op.drop_table("dim_user", schema="game_screw_puzzle_story_schema")
    op.drop_table("dim_item", schema="game_screw_puzzle_story_schema")
    op.drop_table("dim_user", schema="game_celebrity_check_challenge_prank_schema")
    op.drop_table("dim_item", schema="game_celebrity_check_challenge_prank_schema")
    op.drop_table("dim_game", schema="common_dim_schema")
    op.drop_table("dim_show_type", schema="game_xgame_drama_max_schema")
    op.drop_table("dim_package", schema="game_xgame_drama_max_schema")
    op.drop_table("dim_level", schema="game_xgame_drama_max_schema")
    op.drop_table("dim_item_type", schema="game_xgame_drama_max_schema")
    op.drop_table("dim_game_position", schema="game_xgame_drama_max_schema")
    op.drop_table("dim_show_type", schema="game_supermarket_journey_schema")
    op.drop_table("dim_package", schema="game_supermarket_journey_schema")
    op.drop_table("dim_level", schema="game_supermarket_journey_schema")
    op.drop_table("dim_item_type", schema="game_supermarket_journey_schema")
    op.drop_table("dim_game_position", schema="game_supermarket_journey_schema")
    op.drop_table("dim_show_type", schema="game_screw_puzzle_story_schema")
    op.drop_table("dim_package", schema="game_screw_puzzle_story_schema")
    op.drop_table("dim_level", schema="game_screw_puzzle_story_schema")
    op.drop_table("dim_item_type", schema="game_screw_puzzle_story_schema")
    op.drop_table("dim_game_position", schema="game_screw_puzzle_story_schema")
    op.drop_table("dim_show_type", schema="game_celebrity_check_challenge_prank_schema")
    op.drop_table("dim_package", schema="game_celebrity_check_challenge_prank_schema")
    op.drop_table(
        "dim_movie_type", schema="game_celebrity_check_challenge_prank_schema"
    )
    op.drop_table("dim_level", schema="game_celebrity_check_challenge_prank_schema")
    op.drop_table("dim_item_type", schema="game_celebrity_check_challenge_prank_schema")
    op.drop_table(
        "dim_game_position", schema="game_celebrity_check_challenge_prank_schema"
    )
    op.drop_table("dim_time", schema="common_dim_schema")
    op.drop_table("dim_platform", schema="common_dim_schema")
    op.drop_table("dim_location", schema="common_dim_schema")
    op.drop_table("dim_genre", schema="common_dim_schema")
    op.drop_table("dim_event_type", schema="common_dim_schema")
    op.drop_table("dim_device", schema="common_dim_schema")
    op.drop_table("dim_date", schema="common_dim_schema")
    op.drop_table("dim_currency", schema="common_dim_schema")
    op.drop_table("dim_ad", schema="common_dim_schema")
    op.execute(sa.text("DROP SCHEMA IF NOT EXISTS common_dim_schema"))
    op.execute(sa.text("DROP SCHEMA IF NOT EXISTS game_screw_puzzle_story_schema"))
    op.execute(sa.text("DROP SCHEMA IF NOT EXISTS game_supermarket_journey_schema"))
    op.execute(
        sa.text("DROP SCHEMA IF NOT EXISTS game_celebrity_check_challenge_prank_schema")
    )
    op.execute(sa.text("DROP SCHEMA IF NOT EXISTS game_xgame_drama_max_schema"))
    # ### end Alembic commands ###
