"""add fact_user_login add fact_purchase_fail_report

Revision ID: 7dd5f3d23585
Revises: 5c7be0cf6662
Create Date: 2025-04-29 07:40:13.655634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd5f3d23585'
down_revision: Union[str, None] = '5c7be0cf6662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_purchase_fail_report',
    sa.Column('purchase_fail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('date_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('other_reason', sa.String(), nullable=True),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_xgame_drama_max_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_xgame_drama_max_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('purchase_fail_id'),
    sa.UniqueConstraint('purchase_fail_id'),
    schema='game_xgame_drama_max_schema'
    )
    op.create_table('fact_user_login',
    sa.Column('user_login_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('date_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('mail', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_xgame_drama_max_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_xgame_drama_max_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('user_login_id'),
    sa.UniqueConstraint('user_login_id'),
    schema='game_xgame_drama_max_schema'
    )
    op.drop_table('dim_language')
    op.create_unique_constraint(None, 'dim_language', ['language_id'], schema='common_dim_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dim_language', schema='common_dim_schema', type_='unique')
    op.create_table('dim_language',
    sa.Column('language_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('language_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('language_id', name='dim_language_pkey'),
    sa.UniqueConstraint('language_code', name='dim_language_language_code_key')
    )
    op.drop_table('fact_user_login', schema='game_xgame_drama_max_schema')
    op.drop_table('fact_purchase_fail_report', schema='game_xgame_drama_max_schema')
    # ### end Alembic commands ###
