"""add api_call_type

Revision ID: 9b301b4b3152
Revises: a6253c6f6a24
Create Date: 2025-03-25 04:23:30.784168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b301b4b3152'
down_revision: Union[str, None] = 'a6253c6f6a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_api_type',
    sa.Column('api_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_type_name', sa.String(), nullable=True),
    sa.Column('api_type_desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('api_type_id'),
    sa.UniqueConstraint('api_type_id'),
    schema='game_xgame_drama_max_schema'
    )
    op.create_table('fact_api_call',
    sa.Column('api_call_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_type_id', sa.Integer(), nullable=True),
    sa.Column('api_call_duration', sa.Integer(), nullable=True),
    sa.Column('api_call_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['api_type_id'], ['game_xgame_drama_max_schema.dim_api_type.api_type_id'], ),
    sa.PrimaryKeyConstraint('api_call_id'),
    sa.UniqueConstraint('api_call_id'),
    schema='game_xgame_drama_max_schema'
    )
    op.create_unique_constraint(None, 'dim_game_position', ['game_position_id'], schema='game_test_app_schema')
    op.create_unique_constraint(None, 'dim_game_version', ['version_id'], schema='game_test_app_schema')
    op.create_unique_constraint(None, 'dim_item', ['item_id'], schema='game_test_app_schema')
    op.create_unique_constraint(None, 'dim_item_type', ['item_type_id'], schema='game_test_app_schema')
    op.create_unique_constraint(None, 'dim_level', ['level_id'], schema='game_test_app_schema')
    op.create_unique_constraint(None, 'dim_movie_type', ['movie_type_id'], schema='game_test_app_schema')
    op.create_unique_constraint(None, 'dim_package', ['package_id'], schema='game_test_app_schema')
    op.create_unique_constraint(None, 'dim_show_type', ['show_type_id'], schema='game_test_app_schema')
    op.create_unique_constraint(None, 'dim_user', ['user_id'], schema='game_test_app_schema')
    op.create_unique_constraint(None, 'fact_ad_view', ['ad_view_id'], schema='game_test_app_schema')
    op.create_unique_constraint(None, 'fact_iap', ['iap_id'], schema='game_test_app_schema')
    op.create_unique_constraint(None, 'fact_item_transaction', ['transaction_id'], schema='game_test_app_schema')
    op.create_unique_constraint(None, 'fact_movie_info', ['movie_info_id'], schema='game_test_app_schema')
    op.create_unique_constraint(None, 'fact_player_activity', ['activity_id'], schema='game_test_app_schema')
    op.create_unique_constraint(None, 'fact_purchase_action', ['purchase_id'], schema='game_test_app_schema')
    op.create_unique_constraint(None, 'fact_screen', ['screen_id'], schema='game_test_app_schema')
    op.create_unique_constraint(None, 'fact_user_behavior', ['behavior_id'], schema='game_test_app_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_user_behavior', schema='game_test_app_schema', type_='unique')
    op.drop_constraint(None, 'fact_screen', schema='game_test_app_schema', type_='unique')
    op.drop_constraint(None, 'fact_purchase_action', schema='game_test_app_schema', type_='unique')
    op.drop_constraint(None, 'fact_player_activity', schema='game_test_app_schema', type_='unique')
    op.drop_constraint(None, 'fact_movie_info', schema='game_test_app_schema', type_='unique')
    op.drop_constraint(None, 'fact_item_transaction', schema='game_test_app_schema', type_='unique')
    op.drop_constraint(None, 'fact_iap', schema='game_test_app_schema', type_='unique')
    op.drop_constraint(None, 'fact_ad_view', schema='game_test_app_schema', type_='unique')
    op.drop_constraint(None, 'dim_user', schema='game_test_app_schema', type_='unique')
    op.drop_constraint(None, 'dim_show_type', schema='game_test_app_schema', type_='unique')
    op.drop_constraint(None, 'dim_package', schema='game_test_app_schema', type_='unique')
    op.drop_constraint(None, 'dim_movie_type', schema='game_test_app_schema', type_='unique')
    op.drop_constraint(None, 'dim_level', schema='game_test_app_schema', type_='unique')
    op.drop_constraint(None, 'dim_item_type', schema='game_test_app_schema', type_='unique')
    op.drop_constraint(None, 'dim_item', schema='game_test_app_schema', type_='unique')
    op.drop_constraint(None, 'dim_game_version', schema='game_test_app_schema', type_='unique')
    op.drop_constraint(None, 'dim_game_position', schema='game_test_app_schema', type_='unique')
    op.drop_table('fact_api_call', schema='game_xgame_drama_max_schema')
    op.drop_table('dim_api_type', schema='game_xgame_drama_max_schema')
    # ### end Alembic commands ###
