"""edit fact_api_call add column

Revision ID: b96c74a88eb2
Revises: 198c8e4341cb
Create Date: 2025-03-25 04:36:04.490217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b96c74a88eb2'
down_revision: Union[str, None] = '198c8e4341cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_api_call', sa.Column('user_id', sa.Integer(), nullable=True), schema='game_xgame_drama_max_schema')
    op.add_column('fact_api_call', sa.Column('version_id', sa.Integer(), nullable=True), schema='game_xgame_drama_max_schema')
    op.add_column('fact_api_call', sa.Column('event_type_id', sa.Integer(), nullable=True), schema='game_xgame_drama_max_schema')
    op.add_column('fact_api_call', sa.Column('date_id', sa.Integer(), nullable=True), schema='game_xgame_drama_max_schema')
    op.add_column('fact_api_call', sa.Column('time_id', sa.Integer(), nullable=True), schema='game_xgame_drama_max_schema')
    op.add_column('fact_api_call', sa.Column('sequence_id', sa.Integer(), nullable=True), schema='game_xgame_drama_max_schema')
    op.add_column('fact_api_call', sa.Column('batch_id', sa.Integer(), nullable=True), schema='game_xgame_drama_max_schema')
    op.create_foreign_key(None, 'fact_api_call', 'dim_event_type', ['event_type_id'], ['event_type_id'], source_schema='game_xgame_drama_max_schema', referent_schema='common_dim_schema')
    op.create_foreign_key(None, 'fact_api_call', 'dim_date', ['date_id'], ['date_id'], source_schema='game_xgame_drama_max_schema', referent_schema='common_dim_schema')
    op.create_foreign_key(None, 'fact_api_call', 'dim_game_version', ['version_id'], ['version_id'], source_schema='game_xgame_drama_max_schema', referent_schema='game_xgame_drama_max_schema')
    op.create_foreign_key(None, 'fact_api_call', 'dim_time', ['time_id'], ['time_id'], source_schema='game_xgame_drama_max_schema', referent_schema='common_dim_schema')
    op.create_foreign_key(None, 'fact_api_call', 'dim_user', ['user_id'], ['user_id'], source_schema='game_xgame_drama_max_schema', referent_schema='game_xgame_drama_max_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_api_call', schema='game_xgame_drama_max_schema', type_='foreignkey')
    op.drop_constraint(None, 'fact_api_call', schema='game_xgame_drama_max_schema', type_='foreignkey')
    op.drop_constraint(None, 'fact_api_call', schema='game_xgame_drama_max_schema', type_='foreignkey')
    op.drop_constraint(None, 'fact_api_call', schema='game_xgame_drama_max_schema', type_='foreignkey')
    op.drop_constraint(None, 'fact_api_call', schema='game_xgame_drama_max_schema', type_='foreignkey')
    op.drop_column('fact_api_call', 'batch_id', schema='game_xgame_drama_max_schema')
    op.drop_column('fact_api_call', 'sequence_id', schema='game_xgame_drama_max_schema')
    op.drop_column('fact_api_call', 'time_id', schema='game_xgame_drama_max_schema')
    op.drop_column('fact_api_call', 'date_id', schema='game_xgame_drama_max_schema')
    op.drop_column('fact_api_call', 'event_type_id', schema='game_xgame_drama_max_schema')
    op.drop_column('fact_api_call', 'version_id', schema='game_xgame_drama_max_schema')
    op.drop_column('fact_api_call', 'user_id', schema='game_xgame_drama_max_schema')
    # ### end Alembic commands ###
