"""add hand init_movie

Revision ID: c5851adcb954
Revises: 3e9baba5c17b
Create Date: 2025-03-25 09:38:49.231147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5851adcb954'
down_revision: Union[str, None] = '3e9baba5c17b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_movie_place',
    sa.Column('movie_place_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_place_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('movie_place_id'),
    sa.UniqueConstraint('movie_place_id'),
    schema='game_xgame_drama_max_schema'
    )
    op.create_table('fact_init_movie',
    sa.Column('init_movie_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('date_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('movie_place_id', sa.Integer(), nullable=True),
    sa.Column('movie_type', sa.String(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('movie_ep_id', sa.Integer(), nullable=True),
    sa.Column('movie_status', sa.Boolean(), nullable=True),
    sa.Column('movie_duration', sa.Integer(), nullable=True),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['event_type_id'], ['common_dim_schema.dim_event_type.event_type_id'], ),
    sa.ForeignKeyConstraint(['movie_place_id'], ['game_xgame_drama_max_schema.dim_movie_place.movie_place_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_xgame_drama_max_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_xgame_drama_max_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('init_movie_id'),
    sa.UniqueConstraint('init_movie_id'),
    schema='game_xgame_drama_max_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_init_movie', schema='game_xgame_drama_max_schema')
    op.drop_table('dim_movie_place', schema='game_xgame_drama_max_schema')
    # ### end Alembic commands ###
