"""add dim_movie_type

Revision ID: d9acdc7be769
Revises: b96c74a88eb2
Create Date: 2025-03-25 07:31:11.208838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9acdc7be769'
down_revision: Union[str, None] = 'b96c74a88eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_movie_type',
    sa.Column('movie_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_type_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('movie_type_id'),
    sa.UniqueConstraint('movie_type_id'),
    schema='game_xgame_drama_max_schema'
    )
    op.create_table('fact_movie_info',
    sa.Column('movie_info_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('movie_type_id', sa.Integer(), nullable=True),
    sa.Column('movie_date_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('movie_category', sa.Integer(), nullable=True),
    sa.Column('ep_id', sa.Integer(), nullable=True),
    sa.Column('time_watching', sa.Integer(), nullable=True),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['movie_type_id'], ['game_xgame_drama_max_schema.dim_movie_type.movie_type_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_xgame_drama_max_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_xgame_drama_max_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('movie_info_id'),
    sa.UniqueConstraint('movie_info_id'),
    schema='game_xgame_drama_max_schema'
    )
    op.alter_column('dim_package', 'package_name',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=100),
               existing_nullable=True,
               schema='game_xgame_drama_max_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dim_package', 'package_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True,
               schema='game_xgame_drama_max_schema')
    op.drop_table('fact_movie_info', schema='game_xgame_drama_max_schema')
    op.drop_table('dim_movie_type', schema='game_xgame_drama_max_schema')
    # ### end Alembic commands ###
