"""Add_column_to_fact_movie_info_and_fix_size_language_code

Revision ID: f42c3dfe0b65
Revises: 7dd5f3d23585
Create Date: 2025-05-07 08:46:28.184305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42c3dfe0b65'
down_revision: Union[str, None] = '7dd5f3d23585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dim_language', 'language_code',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=3),
               existing_nullable=True,
               schema='common_dim_schema')
    op.add_column('fact_movie_info', sa.Column('language_id', sa.Integer(), nullable=True), schema='game_xgame_drama_max_schema')
    op.create_foreign_key(None, 'fact_movie_info', 'dim_language', ['language_id'], ['language_id'], source_schema='game_xgame_drama_max_schema', referent_schema='common_dim_schema')
    op.create_unique_constraint(None, 'fact_purchase_fail_report', ['purchase_fail_id'], schema='game_xgame_drama_max_schema')
    op.create_unique_constraint(None, 'fact_user_login', ['user_login_id'], schema='game_xgame_drama_max_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_user_login', schema='game_xgame_drama_max_schema', type_='unique')
    op.drop_constraint(None, 'fact_purchase_fail_report', schema='game_xgame_drama_max_schema', type_='unique')
    op.drop_constraint(None, 'fact_movie_info', schema='game_xgame_drama_max_schema', type_='foreignkey')
    op.drop_column('fact_movie_info', 'language_id', schema='game_xgame_drama_max_schema')
    op.alter_column('dim_language', 'language_code',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True,
               schema='common_dim_schema')
    # ### end Alembic commands ###
