"""add celebrity check challenge prank

Revision ID: 07eb1a047cff
Revises: e65a4579be13
Create Date: 2025-02-17 03:03:48.831649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07eb1a047cff'
down_revision: Union[str, None] = 'e65a4579be13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(sa.text('CREATE SCHEMA IF NOT EXISTS game_celebrity_check_challenge_schema'))
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_game_position',
    sa.Column('game_position_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('game_position_id'),
    sa.UniqueConstraint('game_position_id'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.create_table('dim_item_type',
    sa.Column('item_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_type_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('item_type_id'),
    sa.UniqueConstraint('item_type_id'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.create_table('dim_level',
    sa.Column('level_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('level_id'),
    sa.UniqueConstraint('level_id'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.create_table('dim_package',
    sa.Column('package_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('package_id'),
    sa.UniqueConstraint('package_id'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.create_table('dim_show_type',
    sa.Column('show_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('show_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('show_type_id'),
    sa.UniqueConstraint('show_type_id'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.create_table('dim_item',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(length=2500), nullable=True),
    sa.Column('item_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_type_id'], ['game_celebrity_check_challenge_schema.dim_item_type.item_type_id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('item_id'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.create_table('dim_user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(length=50), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('registration_date_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['common_dim_schema.dim_device.device_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['common_dim_schema.dim_location.location_id'], ),
    sa.ForeignKeyConstraint(['registration_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.create_table('dim_game_version',
    sa.Column('version_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('start_date_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['common_dim_schema.dim_game.game_id'], ),
    sa.ForeignKeyConstraint(['start_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('version_id'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.create_table('fact_ad_view',
    sa.Column('ad_view_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('view_date_id', sa.Integer(), nullable=True),
    sa.Column('view_time_id', sa.Integer(), nullable=True),
    sa.Column('ad_position_id', sa.Integer(), nullable=True),
    sa.Column('ad_id', sa.Integer(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('load_time', sa.Integer(), nullable=True),
    sa.Column('rewarded', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['common_dim_schema.dim_ad.ad_id'], ),
    sa.ForeignKeyConstraint(['ad_position_id'], ['game_celebrity_check_challenge_schema.dim_game_position.game_position_id'], ),
    sa.ForeignKeyConstraint(['event_type_id'], ['common_dim_schema.dim_event_type.event_type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_schema.dim_game_version.version_id'], ),
    sa.ForeignKeyConstraint(['view_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['view_time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.PrimaryKeyConstraint('ad_view_id'),
    sa.UniqueConstraint('ad_view_id'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.create_table('fact_iap',
    sa.Column('iap_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('iap_date_id', sa.Integer(), nullable=True),
    sa.Column('iap_time_id', sa.Integer(), nullable=True),
    sa.Column('iap_position_id', sa.Integer(), nullable=True),
    sa.Column('show_type_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['iap_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['iap_position_id'], ['game_celebrity_check_challenge_schema.dim_game_position.game_position_id'], ),
    sa.ForeignKeyConstraint(['iap_time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['game_celebrity_check_challenge_schema.dim_package.package_id'], ),
    sa.ForeignKeyConstraint(['show_type_id'], ['game_celebrity_check_challenge_schema.dim_show_type.show_type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('iap_id'),
    sa.UniqueConstraint('iap_id'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.create_table('fact_item_transaction',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('game_position_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['common_dim_schema.dim_event_type.event_type_id'], ),
    sa.ForeignKeyConstraint(['game_position_id'], ['game_celebrity_check_challenge_schema.dim_game_position.game_position_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['game_celebrity_check_challenge_schema.dim_item.item_id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['game_celebrity_check_challenge_schema.dim_level.level_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['transaction_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('transaction_id'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.create_table('fact_level_event',
    sa.Column('level_event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('event_date_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('require_time', sa.Integer(), nullable=True),
    sa.Column('play_type', sa.String(), nullable=True),
    sa.Column('play_index', sa.Integer(), nullable=True),
    sa.Column('play_time', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('bonus_type', sa.String(), nullable=True),
    sa.Column('bonus_amount', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['event_type_id'], ['common_dim_schema.dim_event_type.event_type_id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['game_celebrity_check_challenge_schema.dim_level.level_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('level_event_id'),
    sa.UniqueConstraint('level_event_id'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.create_table('fact_player_activity',
    sa.Column('activity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('date_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('session_count', sa.Integer(), nullable=True),
    sa.Column('active_day', sa.Integer(), nullable=True),
    sa.Column('highest_level_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('activity_id'),
    sa.UniqueConstraint('activity_id'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.create_table('fact_purchase_action',
    sa.Column('purchase_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('purchase_date_id', sa.Integer(), nullable=True),
    sa.Column('purchase_time_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('usd_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_position_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['common_dim_schema.dim_currency.currency_id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['game_celebrity_check_challenge_schema.dim_package.package_id'], ),
    sa.ForeignKeyConstraint(['purchase_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['purchase_position_id'], ['game_celebrity_check_challenge_schema.dim_game_position.game_position_id'], ),
    sa.ForeignKeyConstraint(['purchase_time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('purchase_id'),
    sa.UniqueConstraint('purchase_id'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.create_table('fact_screen',
    sa.Column('screen_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('date_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('screen_name', sa.Integer(), nullable=True),
    sa.Column('id_item', sa.Integer(), nullable=True),
    sa.Column('total_duration', sa.Integer(), nullable=True),
    sa.Column('screen_session', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['event_type_id'], ['common_dim_schema.dim_event_type.event_type_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('screen_id'),
    sa.UniqueConstraint('screen_id'),
    schema='game_celebrity_check_challenge_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_screen', schema='game_celebrity_check_challenge_schema')
    op.drop_table('fact_purchase_action', schema='game_celebrity_check_challenge_schema')
    op.drop_table('fact_player_activity', schema='game_celebrity_check_challenge_schema')
    op.drop_table('fact_level_event', schema='game_celebrity_check_challenge_schema')
    op.drop_table('fact_item_transaction', schema='game_celebrity_check_challenge_schema')
    op.drop_table('fact_iap', schema='game_celebrity_check_challenge_schema')
    op.drop_table('fact_ad_view', schema='game_celebrity_check_challenge_schema')
    op.drop_table('dim_game_version', schema='game_celebrity_check_challenge_schema')
    op.drop_table('dim_user', schema='game_celebrity_check_challenge_schema')
    op.drop_table('dim_item', schema='game_celebrity_check_challenge_schema')
    op.drop_table('dim_show_type', schema='game_celebrity_check_challenge_schema')
    op.drop_table('dim_package', schema='game_celebrity_check_challenge_schema')
    op.drop_table('dim_level', schema='game_celebrity_check_challenge_schema')
    op.drop_table('dim_item_type', schema='game_celebrity_check_challenge_schema')
    op.drop_table('dim_game_position', schema='game_celebrity_check_challenge_schema')
    # ### end Alembic commands ###
