"""add level_id to fact_ad_view for app

Revision ID: 100b1235fb66
Revises: ea3e30001970
Create Date: 2025-02-17 04:52:06.903499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '100b1235fb66'
down_revision: Union[str, None] = 'ea3e30001970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dim_game_position', ['game_position_id'], schema='game_celebrity_check_challenge_prank_schema')
    op.create_unique_constraint(None, 'dim_game_version', ['version_id'], schema='game_celebrity_check_challenge_prank_schema')
    op.create_unique_constraint(None, 'dim_item', ['item_id'], schema='game_celebrity_check_challenge_prank_schema')
    op.create_unique_constraint(None, 'dim_item_type', ['item_type_id'], schema='game_celebrity_check_challenge_prank_schema')
    op.create_unique_constraint(None, 'dim_level', ['level_id'], schema='game_celebrity_check_challenge_prank_schema')
    op.create_unique_constraint(None, 'dim_package', ['package_id'], schema='game_celebrity_check_challenge_prank_schema')
    op.create_unique_constraint(None, 'dim_show_type', ['show_type_id'], schema='game_celebrity_check_challenge_prank_schema')
    op.create_unique_constraint(None, 'dim_user', ['user_id'], schema='game_celebrity_check_challenge_prank_schema')
    op.add_column('fact_ad_view', sa.Column('level_id', sa.Integer(), nullable=True), schema='game_celebrity_check_challenge_prank_schema')
    op.create_unique_constraint(None, 'fact_ad_view', ['ad_view_id'], schema='game_celebrity_check_challenge_prank_schema')
    op.create_foreign_key(None, 'fact_ad_view', 'dim_level', ['level_id'], ['level_id'], source_schema='game_celebrity_check_challenge_prank_schema', referent_schema='game_celebrity_check_challenge_prank_schema')
    op.create_unique_constraint(None, 'fact_iap', ['iap_id'], schema='game_celebrity_check_challenge_prank_schema')
    op.create_unique_constraint(None, 'fact_item_transaction', ['transaction_id'], schema='game_celebrity_check_challenge_prank_schema')
    op.create_unique_constraint(None, 'fact_level_event', ['level_event_id'], schema='game_celebrity_check_challenge_prank_schema')
    op.create_unique_constraint(None, 'fact_player_activity', ['activity_id'], schema='game_celebrity_check_challenge_prank_schema')
    op.create_unique_constraint(None, 'fact_purchase_action', ['purchase_id'], schema='game_celebrity_check_challenge_prank_schema')
    op.create_unique_constraint(None, 'fact_screen', ['screen_id'], schema='game_celebrity_check_challenge_prank_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_screen', schema='game_celebrity_check_challenge_prank_schema', type_='unique')
    op.drop_constraint(None, 'fact_purchase_action', schema='game_celebrity_check_challenge_prank_schema', type_='unique')
    op.drop_constraint(None, 'fact_player_activity', schema='game_celebrity_check_challenge_prank_schema', type_='unique')
    op.drop_constraint(None, 'fact_level_event', schema='game_celebrity_check_challenge_prank_schema', type_='unique')
    op.drop_constraint(None, 'fact_item_transaction', schema='game_celebrity_check_challenge_prank_schema', type_='unique')
    op.drop_constraint(None, 'fact_iap', schema='game_celebrity_check_challenge_prank_schema', type_='unique')
    op.drop_constraint(None, 'fact_ad_view', schema='game_celebrity_check_challenge_prank_schema', type_='foreignkey')
    op.drop_constraint(None, 'fact_ad_view', schema='game_celebrity_check_challenge_prank_schema', type_='unique')
    op.drop_column('fact_ad_view', 'level_id', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_constraint(None, 'dim_user', schema='game_celebrity_check_challenge_prank_schema', type_='unique')
    op.drop_constraint(None, 'dim_show_type', schema='game_celebrity_check_challenge_prank_schema', type_='unique')
    op.drop_constraint(None, 'dim_package', schema='game_celebrity_check_challenge_prank_schema', type_='unique')
    op.drop_constraint(None, 'dim_level', schema='game_celebrity_check_challenge_prank_schema', type_='unique')
    op.drop_constraint(None, 'dim_item_type', schema='game_celebrity_check_challenge_prank_schema', type_='unique')
    op.drop_constraint(None, 'dim_item', schema='game_celebrity_check_challenge_prank_schema', type_='unique')
    op.drop_constraint(None, 'dim_game_version', schema='game_celebrity_check_challenge_prank_schema', type_='unique')
    op.drop_constraint(None, 'dim_game_position', schema='game_celebrity_check_challenge_prank_schema', type_='unique')
    # ### end Alembic commands ###
