"""first initial

Revision ID: 17dbacc5f4fe
Revises: 
Create Date: 2025-01-21 08:01:30.480671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17dbacc5f4fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(sa.text('CREATE SCHEMA IF NOT EXISTS common_dim_schema'))
    op.execute(sa.text('CREATE SCHEMA IF NOT EXISTS game_screw_puzzle_story_schema'))
    op.execute(sa.text('CREATE SCHEMA IF NOT EXISTS game_supermarket_journey_schema'))
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_ad',
    sa.Column('ad_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ad_format', sa.String(length=100), nullable=True),
    sa.Column('ad_platform', sa.String(length=100), nullable=True),
    sa.Column('ad_network', sa.String(length=100), nullable=True),
    sa.Column('ad_position', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ad_id'),
    sa.UniqueConstraint('ad_id'),
    schema='common_dim_schema'
    )
    op.create_table('dim_currency',
    sa.Column('currency_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency_name', sa.String(length=100), nullable=False),
    sa.Column('currency_code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('currency_id'),
    sa.UniqueConstraint('currency_code'),
    sa.UniqueConstraint('currency_id'),
    schema='common_dim_schema'
    )
    op.create_table('dim_date',
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('full_date', sa.Date(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('date_id'),
    sa.UniqueConstraint('date_id'),
    schema='common_dim_schema'
    )
    op.create_table('dim_event_type',
    sa.Column('event_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('event_type_id'),
    sa.UniqueConstraint('event_type_id'),
    schema='common_dim_schema'
    )
    op.create_table('dim_genre',
    sa.Column('genre_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genre_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('genre_id'),
    sa.UniqueConstraint('genre_id'),
    schema='common_dim_schema'
    )
    op.create_table('dim_location',
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('location_id'),
    schema='common_dim_schema'
    )
    op.create_table('dim_platform',
    sa.Column('platform_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_name', sa.String(length=100), nullable=True),
    sa.Column('platform_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('platform_id'),
    sa.UniqueConstraint('platform_id'),
    schema='common_dim_schema'
    )
    op.create_table('dim_time',
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('second', sa.Integer(), nullable=True),
    sa.Column('time_of_day', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('time_id'),
    sa.UniqueConstraint('time_id'),
    schema='common_dim_schema'
    )
    op.create_table('dim_game_position',
    sa.Column('game_position_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('game_position_id'),
    sa.UniqueConstraint('game_position_id'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('dim_item_type',
    sa.Column('item_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_type_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('item_type_id'),
    sa.UniqueConstraint('item_type_id'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('dim_level',
    sa.Column('level_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('level_id'),
    sa.UniqueConstraint('level_id'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('dim_package',
    sa.Column('package_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('package_id'),
    sa.UniqueConstraint('package_id'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('dim_show_type',
    sa.Column('show_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('show_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('show_type_id'),
    sa.UniqueConstraint('show_type_id'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('staging_highest_level_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('highest_level_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('dim_game_position',
    sa.Column('game_position_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('game_position_id'),
    sa.UniqueConstraint('game_position_id'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('dim_item_type',
    sa.Column('item_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_type_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('item_type_id'),
    sa.UniqueConstraint('item_type_id'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('dim_level',
    sa.Column('level_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('level_id'),
    sa.UniqueConstraint('level_id'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('dim_package',
    sa.Column('package_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('package_id'),
    sa.UniqueConstraint('package_id'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('dim_show_type',
    sa.Column('show_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('show_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('show_type_id'),
    sa.UniqueConstraint('show_type_id'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('staging_highest_level_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('highest_level_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('dim_device',
    sa.Column('device_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_info', sa.String(length=100), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['common_dim_schema.dim_platform.platform_id'], ),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('device_id'),
    schema='common_dim_schema'
    )
    op.create_table('dim_game',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(length=100), nullable=True),
    sa.Column('game_name', sa.String(length=100), nullable=True),
    sa.Column('start_date_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['common_dim_schema.dim_genre.genre_id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['common_dim_schema.dim_platform.platform_id'], ),
    sa.ForeignKeyConstraint(['start_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.PrimaryKeyConstraint('game_id'),
    sa.UniqueConstraint('game_id'),
    schema='common_dim_schema'
    )
    op.create_table('dim_item',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=True),
    sa.Column('item_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_type_id'], ['game_screw_puzzle_story_schema.dim_item_type.item_type_id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('item_id'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('dim_user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(length=50), nullable=True),
    sa.Column('registration_date_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('last_login_date_id', sa.Integer(), nullable=True),
    sa.Column('active_day', sa.Integer(), nullable=True),
    sa.Column('highest_level_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_login_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['common_dim_schema.dim_location.location_id'], ),
    sa.ForeignKeyConstraint(['registration_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('fact_retention',
    sa.Column('retention_date_id', sa.Integer(), nullable=False),
    sa.Column('registration_date_id', sa.Integer(), nullable=False),
    sa.Column('d1_retention_percentage', sa.Numeric(), nullable=True),
    sa.Column('d7_retention_percentage', sa.Numeric(), nullable=True),
    sa.Column('d30_retention_percentage', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['registration_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['retention_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.PrimaryKeyConstraint('retention_date_id', 'registration_date_id'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('staging_last_login_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_login_date_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_login_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('dim_item',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=True),
    sa.Column('item_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_type_id'], ['game_supermarket_journey_schema.dim_item_type.item_type_id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('item_id'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('dim_user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(length=50), nullable=True),
    sa.Column('registration_date_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('last_login_date_id', sa.Integer(), nullable=True),
    sa.Column('active_day', sa.Integer(), nullable=True),
    sa.Column('highest_level_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_login_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['common_dim_schema.dim_location.location_id'], ),
    sa.ForeignKeyConstraint(['registration_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('fact_retention',
    sa.Column('retention_date_id', sa.Integer(), nullable=False),
    sa.Column('registration_date_id', sa.Integer(), nullable=False),
    sa.Column('d1_retention_percentage', sa.Numeric(), nullable=True),
    sa.Column('d7_retention_percentage', sa.Numeric(), nullable=True),
    sa.Column('d30_retention_percentage', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['registration_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['retention_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.PrimaryKeyConstraint('retention_date_id', 'registration_date_id'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('staging_last_login_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_login_date_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_login_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('dim_game_version',
    sa.Column('version_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('start_date_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['common_dim_schema.dim_game.game_id'], ),
    sa.ForeignKeyConstraint(['start_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('version_id'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('user_level_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['game_screw_puzzle_story_schema.dim_level.level_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_screw_puzzle_story_schema.dim_user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('dim_game_version',
    sa.Column('version_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('start_date_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['common_dim_schema.dim_game.game_id'], ),
    sa.ForeignKeyConstraint(['start_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('version_id'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('user_level_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['game_supermarket_journey_schema.dim_level.level_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_supermarket_journey_schema.dim_user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('fact_ad_view',
    sa.Column('ad_view_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('view_date_id', sa.Integer(), nullable=True),
    sa.Column('view_time_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('ad_id', sa.Integer(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('load_time', sa.String(length=50), nullable=True),
    sa.Column('rewarded', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['common_dim_schema.dim_ad.ad_id'], ),
    sa.ForeignKeyConstraint(['event_type_id'], ['common_dim_schema.dim_event_type.event_type_id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['game_screw_puzzle_story_schema.dim_game_position.game_position_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_screw_puzzle_story_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_screw_puzzle_story_schema.dim_game_version.version_id'], ),
    sa.ForeignKeyConstraint(['view_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['view_time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.PrimaryKeyConstraint('ad_view_id'),
    sa.UniqueConstraint('ad_view_id'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('fact_iap',
    sa.Column('iap_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('iap_date_id', sa.Integer(), nullable=True),
    sa.Column('iap_time_id', sa.Integer(), nullable=True),
    sa.Column('iap_location_id', sa.Integer(), nullable=True),
    sa.Column('show_type_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['iap_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['iap_location_id'], ['game_screw_puzzle_story_schema.dim_game_position.game_position_id'], ),
    sa.ForeignKeyConstraint(['iap_time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['game_screw_puzzle_story_schema.dim_package.package_id'], ),
    sa.ForeignKeyConstraint(['show_type_id'], ['game_screw_puzzle_story_schema.dim_show_type.show_type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_screw_puzzle_story_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_screw_puzzle_story_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('iap_id'),
    sa.UniqueConstraint('iap_id'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('fact_item_transaction',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('sink', 'source', name='transaction_type_enum'), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['common_dim_schema.dim_event_type.event_type_id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['common_dim_schema.dim_game.game_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['game_screw_puzzle_story_schema.dim_item.item_id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['game_screw_puzzle_story_schema.dim_level.level_id'], ),
    sa.ForeignKeyConstraint(['position'], ['game_screw_puzzle_story_schema.dim_game_position.game_position_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['transaction_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_screw_puzzle_story_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_screw_puzzle_story_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('transaction_id'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('fact_level_event',
    sa.Column('level_event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('event_date_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('require_time', sa.Integer(), nullable=True),
    sa.Column('play_type', sa.String(), nullable=True),
    sa.Column('play_index', sa.Integer(), nullable=True),
    sa.Column('play_time', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('bonus_type', sa.String(), nullable=True),
    sa.Column('bonus_amount', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['event_type_id'], ['common_dim_schema.dim_event_type.event_type_id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['game_screw_puzzle_story_schema.dim_level.level_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_screw_puzzle_story_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_screw_puzzle_story_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('level_event_id'),
    sa.UniqueConstraint('level_event_id'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('fact_player_action',
    sa.Column('action_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('action_date_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=25), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['game_screw_puzzle_story_schema.dim_level.level_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_screw_puzzle_story_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_screw_puzzle_story_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('action_id'),
    sa.UniqueConstraint('action_id'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('fact_purchase_action',
    sa.Column('purchase_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('purchase_date_id', sa.Integer(), nullable=True),
    sa.Column('purchase_time_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('usd_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_location_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['common_dim_schema.dim_currency.currency_id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['game_screw_puzzle_story_schema.dim_package.package_id'], ),
    sa.ForeignKeyConstraint(['purchase_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['purchase_location_id'], ['game_screw_puzzle_story_schema.dim_game_position.game_position_id'], ),
    sa.ForeignKeyConstraint(['purchase_time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_screw_puzzle_story_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_screw_puzzle_story_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('purchase_id'),
    sa.UniqueConstraint('purchase_id'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('user_game_version_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['game_screw_puzzle_story_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_screw_puzzle_story_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('fact_ad_view',
    sa.Column('ad_view_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('view_date_id', sa.Integer(), nullable=True),
    sa.Column('view_time_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('ad_id', sa.Integer(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('load_time', sa.String(length=50), nullable=True),
    sa.Column('rewarded', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['common_dim_schema.dim_ad.ad_id'], ),
    sa.ForeignKeyConstraint(['event_type_id'], ['common_dim_schema.dim_event_type.event_type_id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['game_supermarket_journey_schema.dim_game_position.game_position_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_supermarket_journey_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_supermarket_journey_schema.dim_game_version.version_id'], ),
    sa.ForeignKeyConstraint(['view_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['view_time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.PrimaryKeyConstraint('ad_view_id'),
    sa.UniqueConstraint('ad_view_id'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('fact_iap',
    sa.Column('iap_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('iap_date_id', sa.Integer(), nullable=True),
    sa.Column('iap_time_id', sa.Integer(), nullable=True),
    sa.Column('iap_location_id', sa.Integer(), nullable=True),
    sa.Column('show_type_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['iap_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['iap_location_id'], ['game_supermarket_journey_schema.dim_game_position.game_position_id'], ),
    sa.ForeignKeyConstraint(['iap_time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['game_supermarket_journey_schema.dim_package.package_id'], ),
    sa.ForeignKeyConstraint(['show_type_id'], ['game_supermarket_journey_schema.dim_show_type.show_type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_supermarket_journey_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_supermarket_journey_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('iap_id'),
    sa.UniqueConstraint('iap_id'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('fact_item_transaction',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('sink', 'source', name='transaction_type_enum'), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['common_dim_schema.dim_event_type.event_type_id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['common_dim_schema.dim_game.game_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['game_supermarket_journey_schema.dim_item.item_id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['game_supermarket_journey_schema.dim_level.level_id'], ),
    sa.ForeignKeyConstraint(['position'], ['game_supermarket_journey_schema.dim_game_position.game_position_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['transaction_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_supermarket_journey_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_supermarket_journey_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('transaction_id'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('fact_level_event',
    sa.Column('level_event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('event_date_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('require_time', sa.Integer(), nullable=True),
    sa.Column('play_type', sa.String(), nullable=True),
    sa.Column('play_index', sa.Integer(), nullable=True),
    sa.Column('play_time', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('bonus_type', sa.String(), nullable=True),
    sa.Column('bonus_amount', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['event_type_id'], ['common_dim_schema.dim_event_type.event_type_id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['game_supermarket_journey_schema.dim_level.level_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_supermarket_journey_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_supermarket_journey_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('level_event_id'),
    sa.UniqueConstraint('level_event_id'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('fact_player_action',
    sa.Column('action_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('action_date_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=25), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['game_supermarket_journey_schema.dim_level.level_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_supermarket_journey_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_supermarket_journey_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('action_id'),
    sa.UniqueConstraint('action_id'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('fact_purchase_action',
    sa.Column('purchase_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('purchase_date_id', sa.Integer(), nullable=True),
    sa.Column('purchase_time_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('usd_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_location_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['common_dim_schema.dim_currency.currency_id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['game_supermarket_journey_schema.dim_package.package_id'], ),
    sa.ForeignKeyConstraint(['purchase_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['purchase_location_id'], ['game_supermarket_journey_schema.dim_game_position.game_position_id'], ),
    sa.ForeignKeyConstraint(['purchase_time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_supermarket_journey_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_supermarket_journey_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('purchase_id'),
    sa.UniqueConstraint('purchase_id'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('user_game_version_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['game_supermarket_journey_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_supermarket_journey_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='game_supermarket_journey_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_game_version_progress', schema='game_supermarket_journey_schema')
    op.drop_table('fact_purchase_action', schema='game_supermarket_journey_schema')
    op.drop_table('fact_player_action', schema='game_supermarket_journey_schema')
    op.drop_table('fact_level_event', schema='game_supermarket_journey_schema')
    op.drop_table('fact_item_transaction', schema='game_supermarket_journey_schema')
    op.drop_table('fact_iap', schema='game_supermarket_journey_schema')
    op.drop_table('fact_ad_view', schema='game_supermarket_journey_schema')
    op.drop_table('user_game_version_progress', schema='game_screw_puzzle_story_schema')
    op.drop_table('fact_purchase_action', schema='game_screw_puzzle_story_schema')
    op.drop_table('fact_player_action', schema='game_screw_puzzle_story_schema')
    op.drop_table('fact_level_event', schema='game_screw_puzzle_story_schema')
    op.drop_table('fact_item_transaction', schema='game_screw_puzzle_story_schema')
    op.drop_table('fact_iap', schema='game_screw_puzzle_story_schema')
    op.drop_table('fact_ad_view', schema='game_screw_puzzle_story_schema')
    op.drop_table('user_level_progress', schema='game_supermarket_journey_schema')
    op.drop_table('dim_game_version', schema='game_supermarket_journey_schema')
    op.drop_table('user_level_progress', schema='game_screw_puzzle_story_schema')
    op.drop_table('dim_game_version', schema='game_screw_puzzle_story_schema')
    op.drop_table('staging_last_login_user', schema='game_supermarket_journey_schema')
    op.drop_table('fact_retention', schema='game_supermarket_journey_schema')
    op.drop_table('dim_user', schema='game_supermarket_journey_schema')
    op.drop_table('dim_item', schema='game_supermarket_journey_schema')
    op.drop_table('staging_last_login_user', schema='game_screw_puzzle_story_schema')
    op.drop_table('fact_retention', schema='game_screw_puzzle_story_schema')
    op.drop_table('dim_user', schema='game_screw_puzzle_story_schema')
    op.drop_table('dim_item', schema='game_screw_puzzle_story_schema')
    op.drop_table('dim_game', schema='common_dim_schema')
    op.drop_table('dim_device', schema='common_dim_schema')
    op.drop_table('staging_highest_level_user', schema='game_supermarket_journey_schema')
    op.drop_table('dim_show_type', schema='game_supermarket_journey_schema')
    op.drop_table('dim_package', schema='game_supermarket_journey_schema')
    op.drop_table('dim_level', schema='game_supermarket_journey_schema')
    op.drop_table('dim_item_type', schema='game_supermarket_journey_schema')
    op.drop_table('dim_game_position', schema='game_supermarket_journey_schema')
    op.drop_table('staging_highest_level_user', schema='game_screw_puzzle_story_schema')
    op.drop_table('dim_show_type', schema='game_screw_puzzle_story_schema')
    op.drop_table('dim_package', schema='game_screw_puzzle_story_schema')
    op.drop_table('dim_level', schema='game_screw_puzzle_story_schema')
    op.drop_table('dim_item_type', schema='game_screw_puzzle_story_schema')
    op.drop_table('dim_game_position', schema='game_screw_puzzle_story_schema')
    op.drop_table('dim_time', schema='common_dim_schema')
    op.drop_table('dim_platform', schema='common_dim_schema')
    op.drop_table('dim_location', schema='common_dim_schema')
    op.drop_table('dim_genre', schema='common_dim_schema')
    op.drop_table('dim_event_type', schema='common_dim_schema')
    op.drop_table('dim_date', schema='common_dim_schema')
    op.drop_table('dim_currency', schema='common_dim_schema')
    op.drop_table('dim_ad', schema='common_dim_schema')
    # ### end Alembic commands ###
