"""retype field in fact table

Revision ID: 2f2277cd2135
Revises: 6e235e595c93
Create Date: 2025-02-12 07:06:25.383753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2277cd2135'
down_revision: Union[str, None] = '6e235e595c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fact_ad_view', 'load_time',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               postgresql_using="load_time::integer",
               existing_nullable=True,
               schema='game_screw_puzzle_story_schema')
    op.alter_column('fact_ad_view', 'rewarded',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               postgresql_using="load_time::integer",
               existing_nullable=True,
               schema='game_screw_puzzle_story_schema')
    op.alter_column('fact_item_transaction', 'transaction_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               schema='game_screw_puzzle_story_schema')
    op.alter_column('fact_item_transaction', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='game_screw_puzzle_story_schema')
    op.alter_column('fact_ad_view', 'load_time',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               postgresql_using="load_time::integer",
               existing_nullable=True,
               schema='game_supermarket_journey_schema')
    op.alter_column('fact_ad_view', 'rewarded',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               postgresql_using="load_time::integer",
               existing_nullable=True,
               schema='game_supermarket_journey_schema')
    op.alter_column('fact_item_transaction', 'transaction_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               schema='game_supermarket_journey_schema')
    op.alter_column('fact_item_transaction', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='game_supermarket_journey_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fact_item_transaction', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='game_supermarket_journey_schema')
    op.alter_column('fact_item_transaction', 'transaction_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               schema='game_supermarket_journey_schema')
    op.alter_column('fact_ad_view', 'rewarded',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               schema='game_supermarket_journey_schema')
    op.alter_column('fact_ad_view', 'load_time',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               schema='game_supermarket_journey_schema')
    op.alter_column('fact_item_transaction', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='game_screw_puzzle_story_schema')
    op.alter_column('fact_item_transaction', 'transaction_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               schema='game_screw_puzzle_story_schema')
    op.alter_column('fact_ad_view', 'rewarded',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               schema='game_screw_puzzle_story_schema')
    op.alter_column('fact_ad_view', 'load_time',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               schema='game_screw_puzzle_story_schema')
    # ### end Alembic commands ###
