"""remove ad_position from dim_ad

Revision ID: 67bbe4a97aaa
Revises: 7e137e1c82de
Create Date: 2025-02-11 01:56:00.902231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67bbe4a97aaa'
down_revision: Union[str, None] = '7e137e1c82de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_ad', 'ad_position', schema='common_dim_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_ad', sa.Column('ad_position', sa.VARCHAR(length=100), autoincrement=False, nullable=True), schema='common_dim_schema')
    # ### end Alembic commands ###
