"""rename position_id to ad_position_id in fact table

Revision ID: 6e235e595c93
Revises: 79be0c32c724
Create Date: 2025-02-12 03:28:45.929192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e235e595c93'
down_revision: Union[str, None] = '79be0c32c724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dim_ad', schema='game_supermarket_journey_schema')
    op.add_column('fact_ad_view', sa.Column('ad_position_id', sa.Integer(), nullable=True), schema='game_screw_puzzle_story_schema')
    op.drop_constraint('fact_ad_view_position_id_fkey', 'fact_ad_view', schema='game_screw_puzzle_story_schema', type_='foreignkey')
    op.create_foreign_key(None, 'fact_ad_view', 'dim_game_position', ['ad_position_id'], ['game_position_id'], source_schema='game_screw_puzzle_story_schema', referent_schema='game_screw_puzzle_story_schema')
    op.drop_column('fact_ad_view', 'position_id', schema='game_screw_puzzle_story_schema')
    op.add_column('fact_ad_view', sa.Column('ad_position_id', sa.Integer(), nullable=True), schema='game_supermarket_journey_schema')
    op.drop_constraint('fact_ad_view_position_id_fkey', 'fact_ad_view', schema='game_supermarket_journey_schema', type_='foreignkey')
    op.create_foreign_key(None, 'fact_ad_view', 'dim_game_position', ['ad_position_id'], ['game_position_id'], source_schema='game_supermarket_journey_schema', referent_schema='game_supermarket_journey_schema')
    op.drop_column('fact_ad_view', 'position_id', schema='game_supermarket_journey_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_ad_view', sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_supermarket_journey_schema')
    op.drop_constraint(None, 'fact_ad_view', schema='game_supermarket_journey_schema', type_='foreignkey')
    op.create_foreign_key('fact_ad_view_position_id_fkey', 'fact_ad_view', 'dim_game_position', ['position_id'], ['game_position_id'], source_schema='game_supermarket_journey_schema', referent_schema='game_supermarket_journey_schema')
    op.drop_column('fact_ad_view', 'ad_position_id', schema='game_supermarket_journey_schema')
    op.add_column('fact_ad_view', sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_screw_puzzle_story_schema')
    op.drop_constraint(None, 'fact_ad_view', schema='game_screw_puzzle_story_schema', type_='foreignkey')
    op.create_foreign_key('fact_ad_view_position_id_fkey', 'fact_ad_view', 'dim_game_position', ['position_id'], ['game_position_id'], source_schema='game_screw_puzzle_story_schema', referent_schema='game_screw_puzzle_story_schema')
    op.drop_column('fact_ad_view', 'ad_position_id', schema='game_screw_puzzle_story_schema')
    op.create_table('dim_ad',
    sa.Column('ad_format', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ad_platform', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ad_network', sa.TEXT(), autoincrement=False, nullable=True),
    schema='game_supermarket_journey_schema'
    )
    # ### end Alembic commands ###
