"""add sequence_id to fact table

Revision ID: 7499be60fe5c
Revises: 100b1235fb66
Create Date: 2025-02-17 07:43:30.250864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7499be60fe5c'
down_revision: Union[str, None] = '100b1235fb66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_user_behavior',
    sa.Column('behavior_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('behavior_date_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('screen_name', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['behavior_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_prank_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_prank_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('behavior_id'),
    sa.UniqueConstraint('behavior_id'),
    schema='game_celebrity_check_challenge_prank_schema'
    )
    op.add_column('fact_ad_view', sa.Column('sequence_id', sa.Integer(), nullable=True), schema='game_celebrity_check_challenge_prank_schema')
    op.add_column('fact_iap', sa.Column('sequence_id', sa.Integer(), nullable=True), schema='game_celebrity_check_challenge_prank_schema')
    op.add_column('fact_item_transaction', sa.Column('sequence_id', sa.Integer(), nullable=True), schema='game_celebrity_check_challenge_prank_schema')
    op.add_column('fact_level_event', sa.Column('sequence_id', sa.Integer(), nullable=True), schema='game_celebrity_check_challenge_prank_schema')
    op.add_column('fact_purchase_action', sa.Column('sequence_id', sa.Integer(), nullable=True), schema='game_celebrity_check_challenge_prank_schema')
    op.add_column('fact_screen', sa.Column('sequence_id', sa.Integer(), nullable=True), schema='game_celebrity_check_challenge_prank_schema')
    op.add_column('fact_ad_view', sa.Column('sequence_id', sa.Integer(), nullable=True), schema='game_screw_puzzle_story_schema')
    op.add_column('fact_iap', sa.Column('sequence_id', sa.Integer(), nullable=True), schema='game_screw_puzzle_story_schema')
    op.add_column('fact_item_transaction', sa.Column('sequence_id', sa.Integer(), nullable=True), schema='game_screw_puzzle_story_schema')
    op.add_column('fact_level_event', sa.Column('sequence_id', sa.Integer(), nullable=True), schema='game_screw_puzzle_story_schema')
    op.add_column('fact_player_action', sa.Column('sequence_id', sa.Integer(), nullable=True), schema='game_screw_puzzle_story_schema')
    op.add_column('fact_purchase_action', sa.Column('sequence_id', sa.Integer(), nullable=True), schema='game_screw_puzzle_story_schema')
    op.add_column('fact_ad_view', sa.Column('sequence_id', sa.Integer(), nullable=True), schema='game_supermarket_journey_schema')
    op.add_column('fact_iap', sa.Column('sequence_id', sa.Integer(), nullable=True), schema='game_supermarket_journey_schema')
    op.add_column('fact_item_transaction', sa.Column('sequence_id', sa.Integer(), nullable=True), schema='game_supermarket_journey_schema')
    op.add_column('fact_level_event', sa.Column('sequence_id', sa.Integer(), nullable=True), schema='game_supermarket_journey_schema')
    op.add_column('fact_player_action', sa.Column('sequence_id', sa.Integer(), nullable=True), schema='game_supermarket_journey_schema')
    op.add_column('fact_purchase_action', sa.Column('sequence_id', sa.Integer(), nullable=True), schema='game_supermarket_journey_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact_purchase_action', 'sequence_id', schema='game_supermarket_journey_schema')
    op.drop_column('fact_player_action', 'sequence_id', schema='game_supermarket_journey_schema')
    op.drop_column('fact_level_event', 'sequence_id', schema='game_supermarket_journey_schema')
    op.drop_column('fact_item_transaction', 'sequence_id', schema='game_supermarket_journey_schema')
    op.drop_column('fact_iap', 'sequence_id', schema='game_supermarket_journey_schema')
    op.drop_column('fact_ad_view', 'sequence_id', schema='game_supermarket_journey_schema')
    op.drop_column('fact_purchase_action', 'sequence_id', schema='game_screw_puzzle_story_schema')
    op.drop_column('fact_player_action', 'sequence_id', schema='game_screw_puzzle_story_schema')
    op.drop_column('fact_level_event', 'sequence_id', schema='game_screw_puzzle_story_schema')
    op.drop_column('fact_item_transaction', 'sequence_id', schema='game_screw_puzzle_story_schema')
    op.drop_column('fact_iap', 'sequence_id', schema='game_screw_puzzle_story_schema')
    op.drop_column('fact_ad_view', 'sequence_id', schema='game_screw_puzzle_story_schema')
    op.drop_column('fact_screen', 'sequence_id', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_column('fact_purchase_action', 'sequence_id', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_column('fact_level_event', 'sequence_id', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_column('fact_item_transaction', 'sequence_id', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_column('fact_iap', 'sequence_id', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_column('fact_ad_view', 'sequence_id', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_table('fact_user_behavior', schema='game_celebrity_check_challenge_prank_schema')
    # ### end Alembic commands ###
