"""remove transaction type enum from fact table

Revision ID: 79be0c32c724
Revises: 7f39c385b23b
Create Date: 2025-02-12 02:51:55.659238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79be0c32c724'
down_revision: Union[str, None] = '7f39c385b23b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fact_item_transaction', 'transaction_type',
               existing_type=postgresql.ENUM('sink', 'source', name='transaction_type_enum'),
               type_=sa.String(length=20),
               existing_nullable=False,
               schema='game_screw_puzzle_story_schema')
    op.alter_column('fact_item_transaction', 'transaction_type',
               existing_type=postgresql.ENUM('sink', 'source', name='transaction_type_enum'),
               type_=sa.String(length=20),
               existing_nullable=False,
               schema='game_supermarket_journey_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fact_item_transaction', 'transaction_type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('sink', 'source', name='transaction_type_enum'),
               existing_nullable=False,
               schema='game_supermarket_journey_schema')
    op.alter_column('fact_item_transaction', 'transaction_type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('sink', 'source', name='transaction_type_enum'),
               existing_nullable=False,
               schema='game_screw_puzzle_story_schema')
    # ### end Alembic commands ###
