"""rename purchase_location_id to purchase_position_id in fact table

Revision ID: 7e137e1c82de
Revises: c6018593f814
Create Date: 2025-02-10 10:43:11.531985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e137e1c82de'
down_revision: Union[str, None] = 'c6018593f814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_purchase_action', sa.Column('purchase_position_id', sa.Integer(), nullable=True), schema='game_screw_puzzle_story_schema')
    op.drop_constraint('fact_purchase_action_purchase_location_id_fkey', 'fact_purchase_action', schema='game_screw_puzzle_story_schema', type_='foreignkey')
    op.create_foreign_key(None, 'fact_purchase_action', 'dim_game_position', ['purchase_position_id'], ['game_position_id'], source_schema='game_screw_puzzle_story_schema', referent_schema='game_screw_puzzle_story_schema')
    op.drop_column('fact_purchase_action', 'purchase_location_id', schema='game_screw_puzzle_story_schema')
    op.add_column('fact_purchase_action', sa.Column('purchase_position_id', sa.Integer(), nullable=True), schema='game_supermarket_journey_schema')
    op.drop_constraint('fact_purchase_action_purchase_location_id_fkey', 'fact_purchase_action', schema='game_supermarket_journey_schema', type_='foreignkey')
    op.create_foreign_key(None, 'fact_purchase_action', 'dim_game_position', ['purchase_position_id'], ['game_position_id'], source_schema='game_supermarket_journey_schema', referent_schema='game_supermarket_journey_schema')
    op.drop_column('fact_purchase_action', 'purchase_location_id', schema='game_supermarket_journey_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_purchase_action', sa.Column('purchase_location_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_supermarket_journey_schema')
    op.drop_constraint(None, 'fact_purchase_action', schema='game_supermarket_journey_schema', type_='foreignkey')
    op.create_foreign_key('fact_purchase_action_purchase_location_id_fkey', 'fact_purchase_action', 'dim_game_position', ['purchase_location_id'], ['game_position_id'], source_schema='game_supermarket_journey_schema', referent_schema='game_supermarket_journey_schema')
    op.drop_column('fact_purchase_action', 'purchase_position_id', schema='game_supermarket_journey_schema')
    op.add_column('fact_purchase_action', sa.Column('purchase_location_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_screw_puzzle_story_schema')
    op.drop_constraint(None, 'fact_purchase_action', schema='game_screw_puzzle_story_schema', type_='foreignkey')
    op.create_foreign_key('fact_purchase_action_purchase_location_id_fkey', 'fact_purchase_action', 'dim_game_position', ['purchase_location_id'], ['game_position_id'], source_schema='game_screw_puzzle_story_schema', referent_schema='game_screw_puzzle_story_schema')
    op.drop_column('fact_purchase_action', 'purchase_position_id', schema='game_screw_puzzle_story_schema')
    # ### end Alembic commands ###
