"""resize item_name from 100 to 2500 in dim table

Revision ID: 7f39c385b23b
Revises: fe8267b08352
Create Date: 2025-02-11 09:49:31.651262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f39c385b23b'
down_revision: Union[str, None] = 'fe8267b08352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dim_item', 'item_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=2500),
               existing_nullable=True,
               schema='game_screw_puzzle_story_schema')
    op.alter_column('dim_item', 'item_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=2500),
               existing_nullable=True,
               schema='game_supermarket_journey_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dim_item', 'item_name',
               existing_type=sa.String(length=2500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               schema='game_supermarket_journey_schema')
    op.alter_column('dim_item', 'item_name',
               existing_type=sa.String(length=2500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               schema='game_screw_puzzle_story_schema')
    # ### end Alembic commands ###
