"""remove progress table

Revision ID: a87083ab92bf
Revises: c8934b467be9
Create Date: 2025-02-13 06:57:53.180831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a87083ab92bf'
down_revision: Union[str, None] = 'c8934b467be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_game_version_progress', schema='game_supermarket_journey_schema')
    op.drop_table('user_level_progress', schema='game_screw_puzzle_story_schema')
    op.drop_table('user_level_progress', schema='game_supermarket_journey_schema')
    op.drop_table('user_game_version_progress', schema='game_screw_puzzle_story_schema')
    op.add_column('fact_player_activity', sa.Column('version_id', sa.Integer(), nullable=True), schema='game_screw_puzzle_story_schema')
    op.create_unique_constraint(None, 'fact_player_activity', ['activity_id'], schema='game_screw_puzzle_story_schema')
    op.create_foreign_key(None, 'fact_player_activity', 'dim_game_version', ['version_id'], ['version_id'], source_schema='game_screw_puzzle_story_schema', referent_schema='game_screw_puzzle_story_schema')
    op.add_column('fact_player_activity', sa.Column('version_id', sa.Integer(), nullable=True), schema='game_supermarket_journey_schema')
    op.create_unique_constraint(None, 'fact_player_activity', ['activity_id'], schema='game_supermarket_journey_schema')
    op.create_foreign_key(None, 'fact_player_activity', 'dim_game_version', ['version_id'], ['version_id'], source_schema='game_supermarket_journey_schema', referent_schema='game_supermarket_journey_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_player_activity', schema='game_supermarket_journey_schema', type_='foreignkey')
    op.drop_constraint(None, 'fact_player_activity', schema='game_supermarket_journey_schema', type_='unique')
    op.drop_column('fact_player_activity', 'version_id', schema='game_supermarket_journey_schema')
    op.drop_constraint(None, 'fact_player_activity', schema='game_screw_puzzle_story_schema', type_='foreignkey')
    op.drop_constraint(None, 'fact_player_activity', schema='game_screw_puzzle_story_schema', type_='unique')
    op.drop_column('fact_player_activity', 'version_id', schema='game_screw_puzzle_story_schema')
    op.create_table('user_game_version_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['game_screw_puzzle_story_schema.dim_user.user_id'], name='user_game_version_progress_user_id_fkey'),
    sa.ForeignKeyConstraint(['version_id'], ['game_screw_puzzle_story_schema.dim_game_version.version_id'], name='user_game_version_progress_version_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_game_version_progress_pkey'),
    sa.UniqueConstraint('id', name='user_game_version_progress_id_key'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('user_level_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completion_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['game_supermarket_journey_schema.dim_level.level_id'], name='user_level_progress_level_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['game_supermarket_journey_schema.dim_user.user_id'], name='user_level_progress_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_level_progress_pkey'),
    sa.UniqueConstraint('id', name='user_level_progress_id_key'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('user_level_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completion_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['game_screw_puzzle_story_schema.dim_level.level_id'], name='user_level_progress_level_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['game_screw_puzzle_story_schema.dim_user.user_id'], name='user_level_progress_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_level_progress_pkey'),
    sa.UniqueConstraint('id', name='user_level_progress_id_key'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('user_game_version_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['game_supermarket_journey_schema.dim_user.user_id'], name='user_game_version_progress_user_id_fkey'),
    sa.ForeignKeyConstraint(['version_id'], ['game_supermarket_journey_schema.dim_game_version.version_id'], name='user_game_version_progress_version_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_game_version_progress_pkey'),
    sa.UniqueConstraint('id', name='user_game_version_progress_id_key'),
    schema='game_supermarket_journey_schema'
    )
    # ### end Alembic commands ###
