"""remove game_id in fact table

Revision ID: b88623616367
Revises: c8e0a7eb661d
Create Date: 2025-02-07 06:48:08.780776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88623616367'
down_revision: Union[str, None] = 'c8e0a7eb661d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fact_item_transaction_game_id_fkey', 'fact_item_transaction', schema='game_screw_puzzle_story_schema', type_='foreignkey')
    op.drop_column('fact_item_transaction', 'game_id', schema='game_screw_puzzle_story_schema')
    op.drop_constraint('fact_item_transaction_game_id_fkey', 'fact_item_transaction', schema='game_supermarket_journey_schema', type_='foreignkey')
    op.drop_column('fact_item_transaction', 'game_id', schema='game_supermarket_journey_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_item_transaction', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_supermarket_journey_schema')
    op.create_foreign_key('fact_item_transaction_game_id_fkey', 'fact_item_transaction', 'dim_game', ['game_id'], ['game_id'], source_schema='game_supermarket_journey_schema', referent_schema='common_dim_schema')
    op.add_column('fact_item_transaction', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_screw_puzzle_story_schema')
    op.create_foreign_key('fact_item_transaction_game_id_fkey', 'fact_item_transaction', 'dim_game', ['game_id'], ['game_id'], source_schema='game_screw_puzzle_story_schema', referent_schema='common_dim_schema')
    # ### end Alembic commands ###
