"""rename iap_location_id to iap_position_id in fact table

Revision ID: c6018593f814
Revises: b88623616367
Create Date: 2025-02-10 08:50:01.617012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6018593f814'
down_revision: Union[str, None] = 'b88623616367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dim_location', schema='common_dim_schema')
    op.drop_table('dim_user')
    op.add_column('fact_iap', sa.Column('iap_position_id', sa.Integer(), nullable=True), schema='game_screw_puzzle_story_schema')
    op.drop_constraint('fact_iap_iap_location_id_fkey', 'fact_iap', schema='game_screw_puzzle_story_schema', type_='foreignkey')
    op.create_foreign_key(None, 'fact_iap', 'dim_game_position', ['iap_position_id'], ['game_position_id'], source_schema='game_screw_puzzle_story_schema', referent_schema='game_screw_puzzle_story_schema')
    op.drop_column('fact_iap', 'iap_location_id', schema='game_screw_puzzle_story_schema')
    op.add_column('fact_iap', sa.Column('iap_position_id', sa.Integer(), nullable=True), schema='game_supermarket_journey_schema')
    op.drop_constraint('fact_iap_iap_location_id_fkey', 'fact_iap', schema='game_supermarket_journey_schema', type_='foreignkey')
    op.create_foreign_key(None, 'fact_iap', 'dim_game_position', ['iap_position_id'], ['game_position_id'], source_schema='game_supermarket_journey_schema', referent_schema='game_supermarket_journey_schema')
    op.drop_column('fact_iap', 'iap_location_id', schema='game_supermarket_journey_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_iap', sa.Column('iap_location_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_supermarket_journey_schema')
    op.drop_constraint(None, 'fact_iap', schema='game_supermarket_journey_schema', type_='foreignkey')
    op.create_foreign_key('fact_iap_iap_location_id_fkey', 'fact_iap', 'dim_game_position', ['iap_location_id'], ['game_position_id'], source_schema='game_supermarket_journey_schema', referent_schema='game_supermarket_journey_schema')
    op.drop_column('fact_iap', 'iap_position_id', schema='game_supermarket_journey_schema')
    op.add_column('fact_iap', sa.Column('iap_location_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_screw_puzzle_story_schema')
    op.drop_constraint(None, 'fact_iap', schema='game_screw_puzzle_story_schema', type_='foreignkey')
    op.create_foreign_key('fact_iap_iap_location_id_fkey', 'fact_iap', 'dim_game_position', ['iap_location_id'], ['game_position_id'], source_schema='game_screw_puzzle_story_schema', referent_schema='game_screw_puzzle_story_schema')
    op.drop_column('fact_iap', 'iap_position_id', schema='game_screw_puzzle_story_schema')
    op.create_table('dim_user',
    sa.Column('user_uuid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_login_date_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('registration_date_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('highest_level_number', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_table('dim_location',
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True), 
    schema='common_dim_schema'
    )
    # ### end Alembic commands ###
