"""update dim_user and add fact_player_activity

Revision ID: c8934b467be9
Revises: 2f2277cd2135
Create Date: 2025-02-13 06:54:41.400771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8934b467be9'
down_revision: Union[str, None] = '2f2277cd2135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_player_activity',
    sa.Column('activity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('session_count', sa.Integer(), nullable=True),
    sa.Column('active_day', sa.Integer(), nullable=True),
    sa.Column('highest_level_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_screw_puzzle_story_schema.dim_user.user_id'], ),
    sa.PrimaryKeyConstraint('activity_id'),
    sa.UniqueConstraint('activity_id'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('fact_player_activity',
    sa.Column('activity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('session_count', sa.Integer(), nullable=True),
    sa.Column('active_day', sa.Integer(), nullable=True),
    sa.Column('highest_level_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_supermarket_journey_schema.dim_user.user_id'], ),
    sa.PrimaryKeyConstraint('activity_id'),
    sa.UniqueConstraint('activity_id'),
    schema='game_supermarket_journey_schema'
    )
    op.add_column('dim_device', sa.Column('platform', sa.String(length=100), nullable=True), schema='common_dim_schema')
    op.drop_constraint('dim_device_platform_id_fkey', 'dim_device', schema='common_dim_schema', type_='foreignkey')
    op.drop_column('dim_device', 'platform_id', schema='common_dim_schema')
    op.add_column('dim_user', sa.Column('device_id', sa.Integer(), nullable=True), schema='game_screw_puzzle_story_schema')
    op.drop_constraint('dim_user_last_login_date_id_fkey', 'dim_user', schema='game_screw_puzzle_story_schema', type_='foreignkey')
    op.create_foreign_key(None, 'dim_user', 'dim_device', ['device_id'], ['device_id'], source_schema='game_screw_puzzle_story_schema', referent_schema='common_dim_schema')
    op.drop_column('dim_user', 'highest_level_number', schema='game_screw_puzzle_story_schema')
    op.drop_column('dim_user', 'last_login_date_id', schema='game_screw_puzzle_story_schema')
    op.drop_column('dim_user', 'active_day', schema='game_screw_puzzle_story_schema')
    op.add_column('dim_user', sa.Column('device_id', sa.Integer(), nullable=True), schema='game_supermarket_journey_schema')
    op.drop_constraint('dim_user_last_login_date_id_fkey', 'dim_user', schema='game_supermarket_journey_schema', type_='foreignkey')
    op.create_foreign_key(None, 'dim_user', 'dim_device', ['device_id'], ['device_id'], source_schema='game_supermarket_journey_schema', referent_schema='common_dim_schema')
    op.drop_column('dim_user', 'highest_level_number', schema='game_supermarket_journey_schema')
    op.drop_column('dim_user', 'last_login_date_id', schema='game_supermarket_journey_schema')
    op.drop_column('dim_user', 'active_day', schema='game_supermarket_journey_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_user', sa.Column('active_day', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_supermarket_journey_schema')
    op.add_column('dim_user', sa.Column('last_login_date_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_supermarket_journey_schema')
    op.add_column('dim_user', sa.Column('highest_level_number', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_supermarket_journey_schema')
    op.drop_constraint(None, 'dim_user', schema='game_supermarket_journey_schema', type_='foreignkey')
    op.create_foreign_key('dim_user_last_login_date_id_fkey', 'dim_user', 'dim_date', ['last_login_date_id'], ['date_id'], source_schema='game_supermarket_journey_schema', referent_schema='common_dim_schema')
    op.drop_column('dim_user', 'device_id', schema='game_supermarket_journey_schema')
    op.add_column('dim_user', sa.Column('active_day', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_screw_puzzle_story_schema')
    op.add_column('dim_user', sa.Column('last_login_date_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_screw_puzzle_story_schema')
    op.add_column('dim_user', sa.Column('highest_level_number', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_screw_puzzle_story_schema')
    op.drop_constraint(None, 'dim_user', schema='game_screw_puzzle_story_schema', type_='foreignkey')
    op.create_foreign_key('dim_user_last_login_date_id_fkey', 'dim_user', 'dim_date', ['last_login_date_id'], ['date_id'], source_schema='game_screw_puzzle_story_schema', referent_schema='common_dim_schema')
    op.drop_column('dim_user', 'device_id', schema='game_screw_puzzle_story_schema')
    op.add_column('dim_device', sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='common_dim_schema')
    op.create_foreign_key('dim_device_platform_id_fkey', 'dim_device', 'dim_platform', ['platform_id'], ['platform_id'], source_schema='common_dim_schema', referent_schema='common_dim_schema')
    op.drop_column('dim_device', 'platform', schema='common_dim_schema')
    op.drop_table('fact_player_activity', schema='game_supermarket_journey_schema')
    op.drop_table('fact_player_activity', schema='game_screw_puzzle_story_schema')
    # ### end Alembic commands ###
