"""update dim_location

Revision ID: c8e0a7eb661d
Revises: 17dbacc5f4fe
Create Date: 2025-02-07 04:10:10.575334

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c8e0a7eb661d"
down_revision: Union[str, None] = "17dbacc5f4fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "dim_ad", ["ad_id"], schema="common_dim_schema")
    op.create_unique_constraint(
        None, "dim_currency", ["currency_id"], schema="common_dim_schema"
    )
    op.create_unique_constraint(
        None, "dim_date", ["date_id"], schema="common_dim_schema"
    )
    op.create_unique_constraint(
        None, "dim_device", ["device_id"], schema="common_dim_schema"
    )
    op.create_unique_constraint(
        None, "dim_event_type", ["event_type_id"], schema="common_dim_schema"
    )
    op.create_unique_constraint(
        None, "dim_game", ["game_id"], schema="common_dim_schema"
    )
    op.create_unique_constraint(
        None, "dim_genre", ["genre_id"], schema="common_dim_schema"
    )
    op.add_column(
        "dim_location",
        sa.Column("country", sa.String(length=100), nullable=True),
        schema="common_dim_schema",
    )
    op.add_column(
        "dim_location",
        sa.Column("city", sa.String(length=50), nullable=True),
        schema="common_dim_schema",
    )
    op.create_unique_constraint(
        None, "dim_location", ["location_id"], schema="common_dim_schema"
    )
    op.create_unique_constraint(
        None, "dim_platform", ["platform_id"], schema="common_dim_schema"
    )
    op.create_unique_constraint(
        None, "dim_time", ["time_id"], schema="common_dim_schema"
    )
    op.create_unique_constraint(
        None,
        "dim_game_position",
        ["game_position_id"],
        schema="game_screw_puzzle_story_schema",
    )
    op.create_unique_constraint(
        None,
        "dim_game_version",
        ["version_id"],
        schema="game_screw_puzzle_story_schema",
    )
    op.create_unique_constraint(
        None, "dim_item", ["item_id"], schema="game_screw_puzzle_story_schema"
    )
    op.create_unique_constraint(
        None, "dim_item_type", ["item_type_id"], schema="game_screw_puzzle_story_schema"
    )
    op.create_unique_constraint(
        None, "dim_level", ["level_id"], schema="game_screw_puzzle_story_schema"
    )
    op.create_unique_constraint(
        None, "dim_package", ["package_id"], schema="game_screw_puzzle_story_schema"
    )
    op.create_unique_constraint(
        None, "dim_show_type", ["show_type_id"], schema="game_screw_puzzle_story_schema"
    )
    op.create_unique_constraint(
        None, "dim_user", ["user_id"], schema="game_screw_puzzle_story_schema"
    )
    op.create_unique_constraint(
        None, "fact_ad_view", ["ad_view_id"], schema="game_screw_puzzle_story_schema"
    )
    op.create_unique_constraint(
        None, "fact_iap", ["iap_id"], schema="game_screw_puzzle_story_schema"
    )
    op.create_unique_constraint(
        None,
        "fact_item_transaction",
        ["transaction_id"],
        schema="game_screw_puzzle_story_schema",
    )
    op.create_unique_constraint(
        None,
        "fact_level_event",
        ["level_event_id"],
        schema="game_screw_puzzle_story_schema",
    )
    op.create_unique_constraint(
        None,
        "fact_player_action",
        ["action_id"],
        schema="game_screw_puzzle_story_schema",
    )
    op.create_unique_constraint(
        None,
        "fact_purchase_action",
        ["purchase_id"],
        schema="game_screw_puzzle_story_schema",
    )
    op.create_unique_constraint(
        None,
        "staging_highest_level_user",
        ["user_id"],
        schema="game_screw_puzzle_story_schema",
    )
    op.create_unique_constraint(
        None,
        "staging_last_login_user",
        ["user_id"],
        schema="game_screw_puzzle_story_schema",
    )
    op.create_unique_constraint(
        None,
        "user_game_version_progress",
        ["id"],
        schema="game_screw_puzzle_story_schema",
    )
    op.create_unique_constraint(
        None, "user_level_progress", ["id"], schema="game_screw_puzzle_story_schema"
    )
    op.create_unique_constraint(
        None,
        "dim_game_position",
        ["game_position_id"],
        schema="game_supermarket_journey_schema",
    )
    op.create_unique_constraint(
        None,
        "dim_game_version",
        ["version_id"],
        schema="game_supermarket_journey_schema",
    )
    op.create_unique_constraint(
        None, "dim_item", ["item_id"], schema="game_supermarket_journey_schema"
    )
    op.create_unique_constraint(
        None,
        "dim_item_type",
        ["item_type_id"],
        schema="game_supermarket_journey_schema",
    )
    op.create_unique_constraint(
        None, "dim_level", ["level_id"], schema="game_supermarket_journey_schema"
    )
    op.create_unique_constraint(
        None, "dim_package", ["package_id"], schema="game_supermarket_journey_schema"
    )
    op.create_unique_constraint(
        None,
        "dim_show_type",
        ["show_type_id"],
        schema="game_supermarket_journey_schema",
    )
    op.create_unique_constraint(
        None, "dim_user", ["user_id"], schema="game_supermarket_journey_schema"
    )
    op.create_unique_constraint(
        None, "fact_ad_view", ["ad_view_id"], schema="game_supermarket_journey_schema"
    )
    op.create_unique_constraint(
        None, "fact_iap", ["iap_id"], schema="game_supermarket_journey_schema"
    )
    op.create_unique_constraint(
        None,
        "fact_item_transaction",
        ["transaction_id"],
        schema="game_supermarket_journey_schema",
    )
    op.create_unique_constraint(
        None,
        "fact_level_event",
        ["level_event_id"],
        schema="game_supermarket_journey_schema",
    )
    op.create_unique_constraint(
        None,
        "fact_player_action",
        ["action_id"],
        schema="game_supermarket_journey_schema",
    )
    op.create_unique_constraint(
        None,
        "fact_purchase_action",
        ["purchase_id"],
        schema="game_supermarket_journey_schema",
    )
    op.create_unique_constraint(
        None,
        "staging_highest_level_user",
        ["user_id"],
        schema="game_supermarket_journey_schema",
    )
    op.create_unique_constraint(
        None,
        "staging_last_login_user",
        ["user_id"],
        schema="game_supermarket_journey_schema",
    )
    op.create_unique_constraint(
        None,
        "user_game_version_progress",
        ["id"],
        schema="game_supermarket_journey_schema",
    )
    op.create_unique_constraint(
        None, "user_level_progress", ["id"], schema="game_supermarket_journey_schema"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None,
        "user_level_progress",
        schema="game_supermarket_journey_schema",
        type_="unique",
    )
    op.drop_constraint(
        None,
        "user_game_version_progress",
        schema="game_supermarket_journey_schema",
        type_="unique",
    )
    op.drop_constraint(
        None,
        "staging_last_login_user",
        schema="game_supermarket_journey_schema",
        type_="unique",
    )
    op.drop_constraint(
        None,
        "staging_highest_level_user",
        schema="game_supermarket_journey_schema",
        type_="unique",
    )
    op.drop_constraint(
        None,
        "fact_purchase_action",
        schema="game_supermarket_journey_schema",
        type_="unique",
    )
    op.drop_constraint(
        None,
        "fact_player_action",
        schema="game_supermarket_journey_schema",
        type_="unique",
    )
    op.drop_constraint(
        None,
        "fact_level_event",
        schema="game_supermarket_journey_schema",
        type_="unique",
    )
    op.drop_constraint(
        None,
        "fact_item_transaction",
        schema="game_supermarket_journey_schema",
        type_="unique",
    )
    op.drop_constraint(
        None, "fact_iap", schema="game_supermarket_journey_schema", type_="unique"
    )
    op.drop_constraint(
        None, "fact_ad_view", schema="game_supermarket_journey_schema", type_="unique"
    )
    op.drop_constraint(
        None, "dim_user", schema="game_supermarket_journey_schema", type_="unique"
    )
    op.drop_constraint(
        None, "dim_show_type", schema="game_supermarket_journey_schema", type_="unique"
    )
    op.drop_constraint(
        None, "dim_package", schema="game_supermarket_journey_schema", type_="unique"
    )
    op.drop_constraint(
        None, "dim_level", schema="game_supermarket_journey_schema", type_="unique"
    )
    op.drop_constraint(
        None, "dim_item_type", schema="game_supermarket_journey_schema", type_="unique"
    )
    op.drop_constraint(
        None, "dim_item", schema="game_supermarket_journey_schema", type_="unique"
    )
    op.drop_constraint(
        None,
        "dim_game_version",
        schema="game_supermarket_journey_schema",
        type_="unique",
    )
    op.drop_constraint(
        None,
        "dim_game_position",
        schema="game_supermarket_journey_schema",
        type_="unique",
    )
    op.drop_constraint(
        None,
        "user_level_progress",
        schema="game_screw_puzzle_story_schema",
        type_="unique",
    )
    op.drop_constraint(
        None,
        "user_game_version_progress",
        schema="game_screw_puzzle_story_schema",
        type_="unique",
    )
    op.drop_constraint(
        None,
        "staging_last_login_user",
        schema="game_screw_puzzle_story_schema",
        type_="unique",
    )
    op.drop_constraint(
        None,
        "staging_highest_level_user",
        schema="game_screw_puzzle_story_schema",
        type_="unique",
    )
    op.drop_constraint(
        None,
        "fact_purchase_action",
        schema="game_screw_puzzle_story_schema",
        type_="unique",
    )
    op.drop_constraint(
        None,
        "fact_player_action",
        schema="game_screw_puzzle_story_schema",
        type_="unique",
    )
    op.drop_constraint(
        None,
        "fact_level_event",
        schema="game_screw_puzzle_story_schema",
        type_="unique",
    )
    op.drop_constraint(
        None,
        "fact_item_transaction",
        schema="game_screw_puzzle_story_schema",
        type_="unique",
    )
    op.drop_constraint(
        None, "fact_iap", schema="game_screw_puzzle_story_schema", type_="unique"
    )
    op.drop_constraint(
        None, "fact_ad_view", schema="game_screw_puzzle_story_schema", type_="unique"
    )
    op.drop_constraint(
        None, "dim_user", schema="game_screw_puzzle_story_schema", type_="unique"
    )
    op.drop_constraint(
        None, "dim_show_type", schema="game_screw_puzzle_story_schema", type_="unique"
    )
    op.drop_constraint(
        None, "dim_package", schema="game_screw_puzzle_story_schema", type_="unique"
    )
    op.drop_constraint(
        None, "dim_level", schema="game_screw_puzzle_story_schema", type_="unique"
    )
    op.drop_constraint(
        None, "dim_item_type", schema="game_screw_puzzle_story_schema", type_="unique"
    )
    op.drop_constraint(
        None, "dim_item", schema="game_screw_puzzle_story_schema", type_="unique"
    )
    op.drop_constraint(
        None,
        "dim_game_version",
        schema="game_screw_puzzle_story_schema",
        type_="unique",
    )
    op.drop_constraint(
        None,
        "dim_game_position",
        schema="game_screw_puzzle_story_schema",
        type_="unique",
    )
    op.drop_constraint(None, "dim_time", schema="common_dim_schema", type_="unique")
    op.drop_constraint(None, "dim_platform", schema="common_dim_schema", type_="unique")
    op.drop_constraint(None, "dim_location", schema="common_dim_schema", type_="unique")
    op.drop_column("dim_location", "city", schema="common_dim_schema")
    op.drop_column("dim_location", "country", schema="common_dim_schema")
    op.drop_constraint(None, "dim_genre", schema="common_dim_schema", type_="unique")
    op.drop_constraint(None, "dim_game", schema="common_dim_schema", type_="unique")
    op.drop_constraint(
        None, "dim_event_type", schema="common_dim_schema", type_="unique"
    )
    op.drop_constraint(None, "dim_device", schema="common_dim_schema", type_="unique")
    op.drop_constraint(None, "dim_date", schema="common_dim_schema", type_="unique")
    op.drop_constraint(None, "dim_currency", schema="common_dim_schema", type_="unique")
    op.drop_constraint(None, "dim_ad", schema="common_dim_schema", type_="unique")
    # ### end Alembic commands ###
