"""update fact_player_activity

Revision ID: e44a7d57130e
Revises: 7499be60fe5c
Create Date: 2025-02-18 09:18:40.411335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e44a7d57130e'
down_revision: Union[str, None] = '7499be60fe5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_retention', schema='game_screw_puzzle_story_schema')
    op.drop_table('staging_highest_level_user', schema='game_screw_puzzle_story_schema')
    op.drop_table('fact_retention', schema='game_supermarket_journey_schema')
    op.drop_table('staging_highest_level_user', schema='game_supermarket_journey_schema')
    op.drop_table('staging_last_login_user', schema='game_screw_puzzle_story_schema')
    op.drop_table('fact_level_event', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_table('staging_last_login_user', schema='game_supermarket_journey_schema')
    op.add_column('fact_player_activity', sa.Column('retention_day', sa.Integer(), nullable=True), schema='game_celebrity_check_challenge_prank_schema')
    op.drop_column('fact_player_activity', 'session_count', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_column('fact_player_activity', 'highest_level_number', schema='game_celebrity_check_challenge_prank_schema')
    op.create_unique_constraint(None, 'fact_user_behavior', ['behavior_id'], schema='game_celebrity_check_challenge_prank_schema')
    op.add_column('fact_player_activity', sa.Column('retention_day', sa.Integer(), nullable=True), schema='game_screw_puzzle_story_schema')
    op.drop_column('fact_player_activity', 'session_count', schema='game_screw_puzzle_story_schema')
    op.drop_column('fact_player_activity', 'highest_level_number', schema='game_screw_puzzle_story_schema')
    op.add_column('fact_player_activity', sa.Column('retention_day', sa.Integer(), nullable=True), schema='game_supermarket_journey_schema')
    op.drop_index('idx_fact_player_activity_date_id', table_name='fact_player_activity', schema='game_supermarket_journey_schema')
    op.drop_column('fact_player_activity', 'session_count', schema='game_supermarket_journey_schema')
    op.drop_column('fact_player_activity', 'highest_level_number', schema='game_supermarket_journey_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_player_activity', sa.Column('highest_level_number', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_supermarket_journey_schema')
    op.add_column('fact_player_activity', sa.Column('session_count', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_supermarket_journey_schema')
    op.create_index('idx_fact_player_activity_date_id', 'fact_player_activity', ['date_id'], unique=False, schema='game_supermarket_journey_schema')
    op.drop_column('fact_player_activity', 'retention_day', schema='game_supermarket_journey_schema')
    op.add_column('fact_player_activity', sa.Column('highest_level_number', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_screw_puzzle_story_schema')
    op.add_column('fact_player_activity', sa.Column('session_count', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_screw_puzzle_story_schema')
    op.drop_column('fact_player_activity', 'retention_day', schema='game_screw_puzzle_story_schema')
    op.drop_constraint(None, 'fact_user_behavior', schema='game_celebrity_check_challenge_prank_schema', type_='unique')
    op.add_column('fact_player_activity', sa.Column('highest_level_number', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_celebrity_check_challenge_prank_schema')
    op.add_column('fact_player_activity', sa.Column('session_count', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_celebrity_check_challenge_prank_schema')
    op.drop_column('fact_player_activity', 'retention_day', schema='game_celebrity_check_challenge_prank_schema')
    op.create_table('staging_last_login_user',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_login_date_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['last_login_date_id'], ['common_dim_schema.dim_date.date_id'], name='staging_last_login_user_last_login_date_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='staging_last_login_user_pkey'),
    sa.UniqueConstraint('user_id', name='staging_last_login_user_user_id_key'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('fact_level_event',
    sa.Column('level_event_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_date_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('require_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('play_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('play_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('play_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bonus_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bonus_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sequence_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_date_id'], ['common_dim_schema.dim_date.date_id'], name='fact_level_event_event_date_id_fkey'),
    sa.ForeignKeyConstraint(['event_type_id'], ['common_dim_schema.dim_event_type.event_type_id'], name='fact_level_event_event_type_id_fkey'),
    sa.ForeignKeyConstraint(['level_id'], ['game_celebrity_check_challenge_prank_schema.dim_level.level_id'], name='fact_level_event_level_id_fkey'),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], name='fact_level_event_time_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_prank_schema.dim_user.user_id'], name='fact_level_event_user_id_fkey'),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_prank_schema.dim_game_version.version_id'], name='fact_level_event_version_id_fkey'),
    sa.PrimaryKeyConstraint('level_event_id', name='fact_level_event_pkey'),
    sa.UniqueConstraint('level_event_id', name='fact_level_event_level_event_id_key'),
    schema='game_celebrity_check_challenge_prank_schema'
    )
    op.create_table('staging_last_login_user',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_login_date_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['last_login_date_id'], ['common_dim_schema.dim_date.date_id'], name='staging_last_login_user_last_login_date_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='staging_last_login_user_pkey'),
    sa.UniqueConstraint('user_id', name='staging_last_login_user_user_id_key'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('staging_highest_level_user',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('highest_level_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='staging_highest_level_user_pkey'),
    sa.UniqueConstraint('user_id', name='staging_highest_level_user_user_id_key'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('fact_retention',
    sa.Column('retention_date_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('registration_date_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('d1_retention_percentage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('d7_retention_percentage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('d30_retention_percentage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['registration_date_id'], ['common_dim_schema.dim_date.date_id'], name='fact_retention_registration_date_id_fkey'),
    sa.ForeignKeyConstraint(['retention_date_id'], ['common_dim_schema.dim_date.date_id'], name='fact_retention_retention_date_id_fkey'),
    sa.PrimaryKeyConstraint('retention_date_id', 'registration_date_id', name='fact_retention_pkey'),
    schema='game_supermarket_journey_schema'
    )
    op.create_table('staging_highest_level_user',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('highest_level_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='staging_highest_level_user_pkey'),
    sa.UniqueConstraint('user_id', name='staging_highest_level_user_user_id_key'),
    schema='game_screw_puzzle_story_schema'
    )
    op.create_table('fact_retention',
    sa.Column('retention_date_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('registration_date_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('d1_retention_percentage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('d7_retention_percentage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('d30_retention_percentage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['registration_date_id'], ['common_dim_schema.dim_date.date_id'], name='fact_retention_registration_date_id_fkey'),
    sa.ForeignKeyConstraint(['retention_date_id'], ['common_dim_schema.dim_date.date_id'], name='fact_retention_retention_date_id_fkey'),
    sa.PrimaryKeyConstraint('retention_date_id', 'registration_date_id', name='fact_retention_pkey'),
    schema='game_screw_puzzle_story_schema'
    )
    # ### end Alembic commands ###
