"""add level_id to fact_ad_view

Revision ID: e65a4579be13
Revises: a87083ab92bf
Create Date: 2025-02-14 02:53:56.230648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65a4579be13'
down_revision: Union[str, None] = 'a87083ab92bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_ad_view', sa.Column('level_id', sa.Integer(), nullable=True), schema='game_screw_puzzle_story_schema')
    op.create_foreign_key(None, 'fact_ad_view', 'dim_level', ['level_id'], ['level_id'], source_schema='game_screw_puzzle_story_schema', referent_schema='game_screw_puzzle_story_schema')
    op.add_column('fact_ad_view', sa.Column('level_id', sa.Integer(), nullable=True), schema='game_supermarket_journey_schema')
    op.create_foreign_key(None, 'fact_ad_view', 'dim_level', ['level_id'], ['level_id'], source_schema='game_supermarket_journey_schema', referent_schema='game_supermarket_journey_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_ad_view', schema='game_supermarket_journey_schema', type_='foreignkey')
    op.drop_column('fact_ad_view', 'level_id', schema='game_supermarket_journey_schema')
    op.drop_constraint(None, 'fact_ad_view', schema='game_screw_puzzle_story_schema', type_='foreignkey')
    op.drop_column('fact_ad_view', 'level_id', schema='game_screw_puzzle_story_schema')
    # ### end Alembic commands ###
