"""add celebrity check challenge prank schema

Revision ID: ea3e30001970
Revises: 07eb1a047cff
Create Date: 2025-02-17 03:18:34.631567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea3e30001970'
down_revision: Union[str, None] = '07eb1a047cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(sa.text('CREATE SCHEMA IF NOT EXISTS game_celebrity_check_challenge_prank_schema'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_game_position',
    sa.Column('game_position_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('game_position_id'),
    sa.UniqueConstraint('game_position_id'),
    schema='game_celebrity_check_challenge_prank_schema'
    )
    op.create_table('dim_item_type',
    sa.Column('item_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_type_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('item_type_id'),
    sa.UniqueConstraint('item_type_id'),
    schema='game_celebrity_check_challenge_prank_schema'
    )
    op.create_table('dim_level',
    sa.Column('level_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('level_id'),
    sa.UniqueConstraint('level_id'),
    schema='game_celebrity_check_challenge_prank_schema'
    )
    op.create_table('dim_package',
    sa.Column('package_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('package_id'),
    sa.UniqueConstraint('package_id'),
    schema='game_celebrity_check_challenge_prank_schema'
    )
    op.create_table('dim_show_type',
    sa.Column('show_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('show_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('show_type_id'),
    sa.UniqueConstraint('show_type_id'),
    schema='game_celebrity_check_challenge_prank_schema'
    )
    op.create_table('dim_item',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(length=2500), nullable=True),
    sa.Column('item_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_type_id'], ['game_celebrity_check_challenge_prank_schema.dim_item_type.item_type_id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('item_id'),
    schema='game_celebrity_check_challenge_prank_schema'
    )
    op.create_table('dim_user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(length=50), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('registration_date_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['common_dim_schema.dim_device.device_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['common_dim_schema.dim_location.location_id'], ),
    sa.ForeignKeyConstraint(['registration_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id'),
    schema='game_celebrity_check_challenge_prank_schema'
    )
    op.create_table('dim_game_version',
    sa.Column('version_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('start_date_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['common_dim_schema.dim_game.game_id'], ),
    sa.ForeignKeyConstraint(['start_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('version_id'),
    schema='game_celebrity_check_challenge_prank_schema'
    )
    op.create_table('fact_ad_view',
    sa.Column('ad_view_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('view_date_id', sa.Integer(), nullable=True),
    sa.Column('view_time_id', sa.Integer(), nullable=True),
    sa.Column('ad_position_id', sa.Integer(), nullable=True),
    sa.Column('ad_id', sa.Integer(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('load_time', sa.Integer(), nullable=True),
    sa.Column('rewarded', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['common_dim_schema.dim_ad.ad_id'], ),
    sa.ForeignKeyConstraint(['ad_position_id'], ['game_celebrity_check_challenge_prank_schema.dim_game_position.game_position_id'], ),
    sa.ForeignKeyConstraint(['event_type_id'], ['common_dim_schema.dim_event_type.event_type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_prank_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_prank_schema.dim_game_version.version_id'], ),
    sa.ForeignKeyConstraint(['view_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['view_time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.PrimaryKeyConstraint('ad_view_id'),
    sa.UniqueConstraint('ad_view_id'),
    schema='game_celebrity_check_challenge_prank_schema'
    )
    op.create_table('fact_iap',
    sa.Column('iap_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('iap_date_id', sa.Integer(), nullable=True),
    sa.Column('iap_time_id', sa.Integer(), nullable=True),
    sa.Column('iap_position_id', sa.Integer(), nullable=True),
    sa.Column('show_type_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['iap_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['iap_position_id'], ['game_celebrity_check_challenge_prank_schema.dim_game_position.game_position_id'], ),
    sa.ForeignKeyConstraint(['iap_time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['game_celebrity_check_challenge_prank_schema.dim_package.package_id'], ),
    sa.ForeignKeyConstraint(['show_type_id'], ['game_celebrity_check_challenge_prank_schema.dim_show_type.show_type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_prank_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_prank_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('iap_id'),
    sa.UniqueConstraint('iap_id'),
    schema='game_celebrity_check_challenge_prank_schema'
    )
    op.create_table('fact_item_transaction',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('game_position_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['common_dim_schema.dim_event_type.event_type_id'], ),
    sa.ForeignKeyConstraint(['game_position_id'], ['game_celebrity_check_challenge_prank_schema.dim_game_position.game_position_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['game_celebrity_check_challenge_prank_schema.dim_item.item_id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['game_celebrity_check_challenge_prank_schema.dim_level.level_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['transaction_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_prank_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_prank_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('transaction_id'),
    schema='game_celebrity_check_challenge_prank_schema'
    )
    op.create_table('fact_level_event',
    sa.Column('level_event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('event_date_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('require_time', sa.Integer(), nullable=True),
    sa.Column('play_type', sa.String(), nullable=True),
    sa.Column('play_index', sa.Integer(), nullable=True),
    sa.Column('play_time', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('bonus_type', sa.String(), nullable=True),
    sa.Column('bonus_amount', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['event_type_id'], ['common_dim_schema.dim_event_type.event_type_id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['game_celebrity_check_challenge_prank_schema.dim_level.level_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_prank_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_prank_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('level_event_id'),
    sa.UniqueConstraint('level_event_id'),
    schema='game_celebrity_check_challenge_prank_schema'
    )
    op.create_table('fact_player_activity',
    sa.Column('activity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('date_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('session_count', sa.Integer(), nullable=True),
    sa.Column('active_day', sa.Integer(), nullable=True),
    sa.Column('highest_level_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_prank_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_prank_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('activity_id'),
    sa.UniqueConstraint('activity_id'),
    schema='game_celebrity_check_challenge_prank_schema'
    )
    op.create_table('fact_purchase_action',
    sa.Column('purchase_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('purchase_date_id', sa.Integer(), nullable=True),
    sa.Column('purchase_time_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('usd_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_position_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['common_dim_schema.dim_currency.currency_id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['game_celebrity_check_challenge_prank_schema.dim_package.package_id'], ),
    sa.ForeignKeyConstraint(['purchase_date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['purchase_position_id'], ['game_celebrity_check_challenge_prank_schema.dim_game_position.game_position_id'], ),
    sa.ForeignKeyConstraint(['purchase_time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_prank_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_prank_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('purchase_id'),
    sa.UniqueConstraint('purchase_id'),
    schema='game_celebrity_check_challenge_prank_schema'
    )
    op.create_table('fact_screen',
    sa.Column('screen_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('date_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('screen_name', sa.Integer(), nullable=True),
    sa.Column('id_item', sa.Integer(), nullable=True),
    sa.Column('total_duration', sa.Integer(), nullable=True),
    sa.Column('screen_session', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['common_dim_schema.dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['event_type_id'], ['common_dim_schema.dim_event_type.event_type_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_prank_schema.dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_prank_schema.dim_game_version.version_id'], ),
    sa.PrimaryKeyConstraint('screen_id'),
    sa.UniqueConstraint('screen_id'),
    schema='game_celebrity_check_challenge_prank_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_game_position',
    sa.Column('game_position_id', sa.INTEGER(), server_default=sa.text("nextval('game_celebrity_check_challenge_schema.dim_game_position_game_position_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('game_position_id', name='dim_game_position_pkey'),
    schema='game_celebrity_check_challenge_schema',
    postgresql_ignore_search_path=False
    )
    op.create_table('fact_purchase_action',
    sa.Column('purchase_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('purchase_date_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('purchase_time_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('package_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('currency_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usd_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('purchase_position_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['common_dim_schema.dim_currency.currency_id'], name='fact_purchase_action_currency_id_fkey'),
    sa.ForeignKeyConstraint(['package_id'], ['game_celebrity_check_challenge_schema.dim_package.package_id'], name='fact_purchase_action_package_id_fkey'),
    sa.ForeignKeyConstraint(['purchase_date_id'], ['common_dim_schema.dim_date.date_id'], name='fact_purchase_action_purchase_date_id_fkey'),
    sa.ForeignKeyConstraint(['purchase_position_id'], ['game_celebrity_check_challenge_schema.dim_game_position.game_position_id'], name='fact_purchase_action_purchase_position_id_fkey'),
    sa.ForeignKeyConstraint(['purchase_time_id'], ['common_dim_schema.dim_time.time_id'], name='fact_purchase_action_purchase_time_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_schema.dim_user.user_id'], name='fact_purchase_action_user_id_fkey'),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_schema.dim_game_version.version_id'], name='fact_purchase_action_version_id_fkey'),
    sa.PrimaryKeyConstraint('purchase_id', name='fact_purchase_action_pkey'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.create_table('fact_player_activity',
    sa.Column('activity_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('highest_level_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['common_dim_schema.dim_date.date_id'], name='fact_player_activity_date_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_schema.dim_user.user_id'], name='fact_player_activity_user_id_fkey'),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_schema.dim_game_version.version_id'], name='fact_player_activity_version_id_fkey'),
    sa.PrimaryKeyConstraint('activity_id', name='fact_player_activity_pkey'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.create_table('dim_user',
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('game_celebrity_check_challenge_schema.dim_user_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('registration_date_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['common_dim_schema.dim_device.device_id'], name='dim_user_device_id_fkey'),
    sa.ForeignKeyConstraint(['location_id'], ['common_dim_schema.dim_location.location_id'], name='dim_user_location_id_fkey'),
    sa.ForeignKeyConstraint(['registration_date_id'], ['common_dim_schema.dim_date.date_id'], name='dim_user_registration_date_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='dim_user_pkey'),
    schema='game_celebrity_check_challenge_schema',
    postgresql_ignore_search_path=False
    )
    op.create_table('fact_ad_view',
    sa.Column('ad_view_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('view_date_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('view_time_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ad_position_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ad_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('load_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rewarded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['common_dim_schema.dim_ad.ad_id'], name='fact_ad_view_ad_id_fkey'),
    sa.ForeignKeyConstraint(['ad_position_id'], ['game_celebrity_check_challenge_schema.dim_game_position.game_position_id'], name='fact_ad_view_ad_position_id_fkey'),
    sa.ForeignKeyConstraint(['event_type_id'], ['common_dim_schema.dim_event_type.event_type_id'], name='fact_ad_view_event_type_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_schema.dim_user.user_id'], name='fact_ad_view_user_id_fkey'),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_schema.dim_game_version.version_id'], name='fact_ad_view_version_id_fkey'),
    sa.ForeignKeyConstraint(['view_date_id'], ['common_dim_schema.dim_date.date_id'], name='fact_ad_view_view_date_id_fkey'),
    sa.ForeignKeyConstraint(['view_time_id'], ['common_dim_schema.dim_time.time_id'], name='fact_ad_view_view_time_id_fkey'),
    sa.PrimaryKeyConstraint('ad_view_id', name='fact_ad_view_pkey'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.create_table('fact_level_event',
    sa.Column('level_event_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_date_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('require_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('play_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('play_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('play_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bonus_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bonus_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_date_id'], ['common_dim_schema.dim_date.date_id'], name='fact_level_event_event_date_id_fkey'),
    sa.ForeignKeyConstraint(['event_type_id'], ['common_dim_schema.dim_event_type.event_type_id'], name='fact_level_event_event_type_id_fkey'),
    sa.ForeignKeyConstraint(['level_id'], ['game_celebrity_check_challenge_schema.dim_level.level_id'], name='fact_level_event_level_id_fkey'),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], name='fact_level_event_time_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_schema.dim_user.user_id'], name='fact_level_event_user_id_fkey'),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_schema.dim_game_version.version_id'], name='fact_level_event_version_id_fkey'),
    sa.PrimaryKeyConstraint('level_event_id', name='fact_level_event_pkey'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.create_table('dim_item',
    sa.Column('item_id', sa.INTEGER(), server_default=sa.text("nextval('game_celebrity_check_challenge_schema.dim_item_item_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=2500), autoincrement=False, nullable=True),
    sa.Column('item_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_type_id'], ['game_celebrity_check_challenge_schema.dim_item_type.item_type_id'], name='dim_item_item_type_id_fkey'),
    sa.PrimaryKeyConstraint('item_id', name='dim_item_pkey'),
    schema='game_celebrity_check_challenge_schema',
    postgresql_ignore_search_path=False
    )
    op.create_table('dim_show_type',
    sa.Column('show_type_id', sa.INTEGER(), server_default=sa.text("nextval('game_celebrity_check_challenge_schema.dim_show_type_show_type_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('show_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('show_type_id', name='dim_show_type_pkey'),
    schema='game_celebrity_check_challenge_schema',
    postgresql_ignore_search_path=False
    )
    op.create_table('dim_package',
    sa.Column('package_id', sa.INTEGER(), server_default=sa.text("nextval('game_celebrity_check_challenge_schema.dim_package_package_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('package_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('package_id', name='dim_package_pkey'),
    schema='game_celebrity_check_challenge_schema',
    postgresql_ignore_search_path=False
    )
    op.create_table('dim_level',
    sa.Column('level_id', sa.INTEGER(), server_default=sa.text("nextval('game_celebrity_check_challenge_schema.dim_level_level_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('level_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mode', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('level_id', name='dim_level_pkey'),
    schema='game_celebrity_check_challenge_schema',
    postgresql_ignore_search_path=False
    )
    op.create_table('fact_screen',
    sa.Column('screen_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('screen_name', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_item', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('screen_session', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['common_dim_schema.dim_date.date_id'], name='fact_screen_date_id_fkey'),
    sa.ForeignKeyConstraint(['event_type_id'], ['common_dim_schema.dim_event_type.event_type_id'], name='fact_screen_event_type_id_fkey'),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], name='fact_screen_time_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_schema.dim_user.user_id'], name='fact_screen_user_id_fkey'),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_schema.dim_game_version.version_id'], name='fact_screen_version_id_fkey'),
    sa.PrimaryKeyConstraint('screen_id', name='fact_screen_pkey'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.create_table('fact_iap',
    sa.Column('iap_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('iap_date_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('iap_time_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('iap_position_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('show_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('package_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['iap_date_id'], ['common_dim_schema.dim_date.date_id'], name='fact_iap_iap_date_id_fkey'),
    sa.ForeignKeyConstraint(['iap_position_id'], ['game_celebrity_check_challenge_schema.dim_game_position.game_position_id'], name='fact_iap_iap_position_id_fkey'),
    sa.ForeignKeyConstraint(['iap_time_id'], ['common_dim_schema.dim_time.time_id'], name='fact_iap_iap_time_id_fkey'),
    sa.ForeignKeyConstraint(['package_id'], ['game_celebrity_check_challenge_schema.dim_package.package_id'], name='fact_iap_package_id_fkey'),
    sa.ForeignKeyConstraint(['show_type_id'], ['game_celebrity_check_challenge_schema.dim_show_type.show_type_id'], name='fact_iap_show_type_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_schema.dim_user.user_id'], name='fact_iap_user_id_fkey'),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_schema.dim_game_version.version_id'], name='fact_iap_version_id_fkey'),
    sa.PrimaryKeyConstraint('iap_id', name='fact_iap_pkey'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.create_table('dim_item_type',
    sa.Column('item_type_id', sa.INTEGER(), server_default=sa.text("nextval('game_celebrity_check_challenge_schema.dim_item_type_item_type_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('item_type_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('item_type_id', name='dim_item_type_pkey'),
    schema='game_celebrity_check_challenge_schema',
    postgresql_ignore_search_path=False
    )
    op.create_table('dim_game_version',
    sa.Column('version_id', sa.INTEGER(), server_default=sa.text("nextval('game_celebrity_check_challenge_schema.dim_game_version_version_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('start_date_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['common_dim_schema.dim_game.game_id'], name='dim_game_version_game_id_fkey'),
    sa.ForeignKeyConstraint(['start_date_id'], ['common_dim_schema.dim_date.date_id'], name='dim_game_version_start_date_id_fkey'),
    sa.PrimaryKeyConstraint('version_id', name='dim_game_version_pkey'),
    schema='game_celebrity_check_challenge_schema',
    postgresql_ignore_search_path=False
    )
    op.create_table('fact_item_transaction',
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_date_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('game_position_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['common_dim_schema.dim_event_type.event_type_id'], name='fact_item_transaction_event_type_id_fkey'),
    sa.ForeignKeyConstraint(['game_position_id'], ['game_celebrity_check_challenge_schema.dim_game_position.game_position_id'], name='fact_item_transaction_game_position_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['game_celebrity_check_challenge_schema.dim_item.item_id'], name='fact_item_transaction_item_id_fkey'),
    sa.ForeignKeyConstraint(['level_id'], ['game_celebrity_check_challenge_schema.dim_level.level_id'], name='fact_item_transaction_level_id_fkey'),
    sa.ForeignKeyConstraint(['time_id'], ['common_dim_schema.dim_time.time_id'], name='fact_item_transaction_time_id_fkey'),
    sa.ForeignKeyConstraint(['transaction_date_id'], ['common_dim_schema.dim_date.date_id'], name='fact_item_transaction_transaction_date_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['game_celebrity_check_challenge_schema.dim_user.user_id'], name='fact_item_transaction_user_id_fkey'),
    sa.ForeignKeyConstraint(['version_id'], ['game_celebrity_check_challenge_schema.dim_game_version.version_id'], name='fact_item_transaction_version_id_fkey'),
    sa.PrimaryKeyConstraint('transaction_id', name='fact_item_transaction_pkey'),
    schema='game_celebrity_check_challenge_schema'
    )
    op.drop_table('fact_screen', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_table('fact_purchase_action', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_table('fact_player_activity', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_table('fact_level_event', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_table('fact_item_transaction', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_table('fact_iap', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_table('fact_ad_view', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_table('dim_game_version', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_table('dim_user', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_table('dim_item', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_table('dim_show_type', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_table('dim_package', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_table('dim_level', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_table('dim_item_type', schema='game_celebrity_check_challenge_prank_schema')
    op.drop_table('dim_game_position', schema='game_celebrity_check_challenge_prank_schema')
    # ### end Alembic commands ###
