"""rename position to game_position_id in fact table

Revision ID: fe8267b08352
Revises: 67bbe4a97aaa
Create Date: 2025-02-11 07:08:56.967269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8267b08352'
down_revision: Union[str, None] = '67bbe4a97aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_item_transaction', sa.Column('game_position_id', sa.Integer(), nullable=True), schema='game_screw_puzzle_story_schema')
    op.drop_constraint('fact_item_transaction_position_fkey', 'fact_item_transaction', schema='game_screw_puzzle_story_schema', type_='foreignkey')
    op.create_foreign_key(None, 'fact_item_transaction', 'dim_game_position', ['game_position_id'], ['game_position_id'], source_schema='game_screw_puzzle_story_schema', referent_schema='game_screw_puzzle_story_schema')
    op.drop_column('fact_item_transaction', 'position', schema='game_screw_puzzle_story_schema')
    op.add_column('fact_item_transaction', sa.Column('game_position_id', sa.Integer(), nullable=True), schema='game_supermarket_journey_schema')
    op.drop_constraint('fact_item_transaction_position_fkey', 'fact_item_transaction', schema='game_supermarket_journey_schema', type_='foreignkey')
    op.create_foreign_key(None, 'fact_item_transaction', 'dim_game_position', ['game_position_id'], ['game_position_id'], source_schema='game_supermarket_journey_schema', referent_schema='game_supermarket_journey_schema')
    op.drop_column('fact_item_transaction', 'position', schema='game_supermarket_journey_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_item_transaction', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_supermarket_journey_schema')
    op.drop_constraint(None, 'fact_item_transaction', schema='game_supermarket_journey_schema', type_='foreignkey')
    op.create_foreign_key('fact_item_transaction_position_fkey', 'fact_item_transaction', 'dim_game_position', ['position'], ['game_position_id'], source_schema='game_supermarket_journey_schema', referent_schema='game_supermarket_journey_schema')
    op.drop_column('fact_item_transaction', 'game_position_id', schema='game_supermarket_journey_schema')
    op.add_column('fact_item_transaction', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True), schema='game_screw_puzzle_story_schema')
    op.drop_constraint(None, 'fact_item_transaction', schema='game_screw_puzzle_story_schema', type_='foreignkey')
    op.create_foreign_key('fact_item_transaction_position_fkey', 'fact_item_transaction', 'dim_game_position', ['position'], ['game_position_id'], source_schema='game_screw_puzzle_story_schema', referent_schema='game_screw_puzzle_story_schema')
    op.drop_column('fact_item_transaction', 'game_position_id', schema='game_screw_puzzle_story_schema')
    # ### end Alembic commands ###
